/**
 * Generates `src/routes.gen.ts`: the route table of every contract (id, method, path, response
 * and body kinds) **without Zod schemas**. The typed client only needs this table at runtime, so
 * islands and the console ship the client without Zod or any DTO schema (types stay exact through
 * `import type`).
 *
 *   node scripts/gen-routes.ts          # write src/routes.gen.ts
 *   node scripts/gen-routes.ts --check  # exit 1 if the file is stale
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { allEndpoints } from '../src/contracts.ts';
import { responseKindOf } from '../src/endpoint.ts';

export const ROUTES_FILE = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'routes.gen.ts');

/** Builds the source of `src/routes.gen.ts`. */
export function generateRoutesModule(): string {
  const lines = [
    '// Generated by packages/contracts/scripts/gen-routes.ts from the endpoint contracts — DO NOT EDIT.',
    '// Regenerate with `pnpm gen` (or `pnpm --filter @sotf/contracts gen`).',
    '',
    "import type { BodyKind, HttpMethod, ResponseKind } from './endpoint.ts';",
    '',
    '/** What the client needs to call an endpoint (no schemas). */',
    'export interface RouteSpec {',
    '  readonly id: string;',
    '  readonly method: HttpMethod;',
    '  readonly path: string;',
    '  readonly kind: ResponseKind;',
    '  readonly bodyKind: BodyKind | null;',
    '}',
    '',
    '/** Every endpoint contract, by domain and name. */',
    'export const API_ROUTES = {',
  ];
  let currentDomain = '';
  for (const { domain, name, endpoint } of allEndpoints()) {
    if (domain !== currentDomain) {
      if (currentDomain) lines.push('  },');
      lines.push(`  ${domain}: {`);
      currentDomain = domain;
    }
    const bodyKind = endpoint.body ? `'${endpoint.bodyKind ?? 'json'}'` : 'null';
    lines.push(
      `    ${name}: { id: '${endpoint.id}', method: '${endpoint.method}', path: ${JSON.stringify(endpoint.path)}, kind: '${responseKindOf(endpoint)}', bodyKind: ${bodyKind} },`,
    );
  }
  if (currentDomain) lines.push('  },');
  lines.push('} as const satisfies Readonly<Record<string, Readonly<Record<string, RouteSpec>>>>;', '');
  return lines.join('\n');
}

function main(): void {
  const source = generateRoutesModule();
  if (process.argv.includes('--check')) {
    if (readFileSync(ROUTES_FILE, 'utf8') !== source) {
      process.stderr.write('src/routes.gen.ts is stale: run `pnpm --filter @sotf/contracts gen`\n');
      process.exit(1);
    }
    process.stdout.write('ok routes.gen.ts is up to date\n');
    return;
  }
  writeFileSync(ROUTES_FILE, source);
  process.stdout.write(`ok wrote ${ROUTES_FILE}\n`);
}

if (import.meta.main) main();
