/**
 * Builds every committed brand asset from source:
 *
 *   1. `src/generated/brand-data.gen.ts` (Onest outlines of the initials),
 *   2. the SVG assets (Field kit sprite),
 *   3. the raster assets from `sources/` (scripts/build-icons.ts): logos, favicons, icons, OG,
 *   4. `assets/manifest.json` with the SHA-256 of every file.
 *
 * Usage:
 *   node scripts/build-assets.ts          write everything
 *   node scripts/build-assets.ts --check  rebuild in memory and fail if anything differs
 */

import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { type BuiltFile, buildRasterAssets, log } from './build-icons.ts';
import { generateBrandDataSource } from './lib/sources.ts';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ASSETS = join(ROOT, 'assets');
const GENERATED = join(ROOT, 'src', 'generated', 'brand-data.gen.ts');

function sha256(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

function text(path: string, content: string): BuiltFile {
  return { path, bytes: Buffer.from(content.endsWith('\n') ? content : `${content}\n`, 'utf8') };
}

/** Vector assets: the Field kit icon sprite (the only SVG the site still ships from this package). */
function buildVectorAssets(brand: typeof import('../src/index.ts')): BuiltFile[] {
  return [text('public/brand/field-kit.svg', brand.fieldKitSprite())];
}

function manifest(files: readonly BuiltFile[]): BuiltFile {
  const entries = [...files]
    .sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
    .map((file) => [file.path, { bytes: file.bytes.length, sha256: sha256(file.bytes) }] as const);
  return text(
    'manifest.json',
    JSON.stringify(
      {
        $comment: 'Generated by `pnpm --filter @sotf/brand build:assets`. Do not edit.',
        files: Object.fromEntries(entries),
      },
      null,
      2,
    ),
  );
}

async function listFiles(directory: string): Promise<string[]> {
  if (!existsSync(directory)) {
    return [];
  }
  const entries = await readdir(directory, { recursive: true, withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => relative(ASSETS, join(entry.parentPath, entry.name)).split(sep).join('/'));
}

/**
 * Builds all assets in memory from the brand module. The module is imported dynamically so
 * that `write()` can regenerate `brand-data.gen.ts` first and build from the fresh geometry.
 */
export async function buildAll(): Promise<BuiltFile[]> {
  const brand = (await import(pathToFileURL(join(ROOT, 'src', 'index.ts')).href)) as typeof import('../src/index.ts');
  const files = [...buildVectorAssets(brand), ...(await buildRasterAssets())];
  files.push(manifest(files));
  return files;
}

async function readGenerated(): Promise<string> {
  return existsSync(GENERATED) ? readFile(GENERATED, 'utf8') : '';
}

async function check(): Promise<number> {
  if ((await readGenerated()) !== generateBrandDataSource()) {
    console.error('src/generated/brand-data.gen.ts is out of date with sources/fonts.');
    console.error('Run `pnpm --filter @sotf/brand build:assets` and commit the result.');
    return 1;
  }
  const problems: string[] = [];
  const files = await buildAll();
  const expected = new Set(files.map((file) => file.path));
  for (const file of files) {
    const target = join(ASSETS, file.path);
    if (!existsSync(target)) {
      problems.push(`missing assets/${file.path}`);
      continue;
    }
    const actual = await readFile(target);
    if (!actual.equals(file.bytes)) {
      problems.push(
        `assets/${file.path} differs (sha256 ${sha256(actual).slice(0, 12)} ≠ ${sha256(file.bytes).slice(0, 12)})`,
      );
    }
  }
  for (const path of await listFiles(ASSETS)) {
    if (!expected.has(path)) {
      problems.push(`stale file assets/${path}`);
    }
  }
  if (problems.length > 0) {
    console.error(`Brand assets are not reproducible from source:\n  - ${problems.join('\n  - ')}`);
    console.error('Run `pnpm --filter @sotf/brand build:assets` and commit the result.');
    return 1;
  }
  log(`OK: ${files.length} brand assets match their sources byte for byte.`);
  return 0;
}

async function write(): Promise<void> {
  const source = generateBrandDataSource();
  if ((await readGenerated()) !== source) {
    await mkdir(dirname(GENERATED), { recursive: true });
    await writeFile(GENERATED, source);
    log('wrote src/generated/brand-data.gen.ts');
  }
  const files = await buildAll();
  const expected = new Set(files.map((file) => file.path));
  for (const path of await listFiles(ASSETS)) {
    if (!expected.has(path)) {
      await rm(join(ASSETS, path));
      log(`removed stale assets/${path}`);
    }
  }
  for (const file of files) {
    const target = join(ASSETS, file.path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, file.bytes);
  }
  log(`Wrote ${files.length} brand assets to assets/ (see assets/manifest.json).`);
}

if (import.meta.main) {
  if (process.argv.includes('--check')) {
    process.exitCode = await check();
  } else {
    await write();
  }
}
