/**
 * Static site pages offered by search and Cmd+K (PLAN §4.2, §7.9): key, path and the localised
 * title in the 13 locales. Paths are the English (unprefixed) canonical paths; the web adds the
 * locale prefix, as for every other path returned by the API.
 */
import type { Locale } from '@sotf/contracts/common';

export interface SitePage {
  key: string;
  path: string;
  titles: Readonly<Record<Locale, string>>;
  /** Extra English words that should find the page. */
  keywords: readonly string[];
}

const same = (title: string): Record<Locale, string> => ({
  en: title,
  es: title,
  de: title,
  fr: title,
  it: title,
  nl: title,
  pl: title,
  pt: title,
  ru: title,
  sv: title,
  tr: title,
  zh: title,
  ja: title,
});

export const SITE_PAGES: readonly SitePage[] = [
  {
    key: 'explore',
    path: '/mods',
    keywords: ['browse', 'catalog', 'mods', 'explore'],
    titles: {
      en: 'Explore mods',
      es: 'Explorar mods',
      de: 'Mods entdecken',
      fr: 'Explorer les mods',
      it: 'Esplora le mod',
      nl: 'Mods verkennen',
      pl: 'Przeglądaj mody',
      pt: 'Explorar mods',
      ru: 'Каталог модов',
      sv: 'Utforska moddar',
      tr: 'Modları keşfet',
      zh: '浏览模组',
      ja: 'MODを探す',
    },
  },
  {
    key: 'builds',
    path: '/builds',
    keywords: ['buildshare', 'blueprints', 'bases'],
    titles: {
      en: 'Builds',
      es: 'Construcciones',
      de: 'Bauwerke',
      fr: 'Constructions',
      it: 'Costruzioni',
      nl: 'Bouwwerken',
      pl: 'Budowle',
      pt: 'Construções',
      ru: 'Постройки',
      sv: 'Byggen',
      tr: 'Yapılar',
      zh: '建筑蓝图',
      ja: '建築',
    },
  },
  {
    key: 'kits',
    path: '/kits',
    keywords: ['collections', 'modpacks', 'packs'],
    titles: {
      en: 'Mod kits',
      es: 'Kits de mods',
      de: 'Mod-Kits',
      fr: 'Kits de mods',
      it: 'Kit di mod',
      nl: 'Modkits',
      pl: 'Zestawy modów',
      pt: 'Kits de mods',
      ru: 'Наборы модов',
      sv: 'Moddpaket',
      tr: 'Mod setleri',
      zh: '模组合集',
      ja: 'MODキット',
    },
  },
  {
    key: 'creators',
    path: '/creators',
    keywords: ['authors', 'modders', 'developers'],
    titles: {
      en: 'Creators',
      es: 'Creadores',
      de: 'Ersteller',
      fr: 'Créateurs',
      it: 'Creatori',
      nl: 'Makers',
      pl: 'Twórcy',
      pt: 'Criadores',
      ru: 'Авторы',
      sv: 'Skapare',
      tr: 'Yapımcılar',
      zh: '创作者',
      ja: 'クリエイター',
    },
  },
  {
    key: 'install',
    path: '/install',
    keywords: ['install', 'redloader', 'redmanager', 'setup', 'guide', 'loader'],
    titles: {
      en: 'How to install mods',
      es: 'Cómo instalar mods',
      de: 'Mods installieren',
      fr: 'Installer des mods',
      it: 'Come installare le mod',
      nl: 'Mods installeren',
      pl: 'Jak instalować mody',
      pt: 'Como instalar mods',
      ru: 'Как установить моды',
      sv: 'Så installerar du moddar',
      tr: 'Mod nasıl kurulur',
      zh: '如何安装模组',
      ja: 'MODのインストール方法',
    },
  },
  {
    key: 'patch-radar',
    path: '/patch-radar',
    keywords: ['patch', 'update', 'compatibility', 'broken', 'works'],
    titles: {
      en: 'Patch Radar',
      es: 'Radar de parches',
      de: 'Patch-Radar',
      fr: 'Radar des patchs',
      it: 'Radar delle patch',
      nl: 'Patchradar',
      pl: 'Radar łatek',
      pt: 'Radar de patches',
      ru: 'Радар патчей',
      sv: 'Patchradar',
      tr: 'Yama radarı',
      zh: '补丁雷达',
      ja: 'パッチレーダー',
    },
  },
  {
    key: 'achievements',
    path: '/achievements',
    keywords: ['badges', 'ranks', 'xp'],
    titles: {
      en: 'Achievements',
      es: 'Logros',
      de: 'Erfolge',
      fr: 'Succès',
      it: 'Obiettivi',
      nl: 'Prestaties',
      pl: 'Osiągnięcia',
      pt: 'Conquistas',
      ru: 'Достижения',
      sv: 'Prestationer',
      tr: 'Başarımlar',
      zh: '成就',
      ja: '実績',
    },
  },
  {
    key: 'news',
    path: '/news',
    keywords: ['blog', 'changelog', 'announcements'],
    titles: {
      en: 'News',
      es: 'Noticias',
      de: 'Neuigkeiten',
      fr: 'Actualités',
      it: 'Novità',
      nl: 'Nieuws',
      pl: 'Aktualności',
      pt: 'Notícias',
      ru: 'Новости',
      sv: 'Nyheter',
      tr: 'Haberler',
      zh: '新闻',
      ja: 'ニュース',
    },
  },
  {
    key: 'about',
    path: '/about',
    keywords: ['about', 'team', 'contact'],
    titles: {
      en: 'About SOTF Mods',
      es: 'Acerca de SOTF Mods',
      de: 'Über SOTF Mods',
      fr: 'À propos de SOTF Mods',
      it: 'Informazioni su SOTF Mods',
      nl: 'Over SOTF Mods',
      pl: 'O SOTF Mods',
      pt: 'Sobre o SOTF Mods',
      ru: 'О SOTF Mods',
      sv: 'Om SOTF Mods',
      tr: 'SOTF Mods hakkında',
      zh: '关于 SOTF Mods',
      ja: 'SOTF Modsについて',
    },
  },
  {
    key: 'developers',
    path: '/developers',
    keywords: ['api', 'docs', 'openapi', 'integration'],
    titles: {
      en: 'Developers & API',
      es: 'Desarrolladores y API',
      de: 'Entwickler & API',
      fr: 'Développeurs et API',
      it: 'Sviluppatori e API',
      nl: 'Ontwikkelaars & API',
      pl: 'Deweloperzy i API',
      pt: 'Desenvolvedores e API',
      ru: 'Разработчикам и API',
      sv: 'Utvecklare & API',
      tr: 'Geliştiriciler ve API',
      zh: '开发者与 API',
      ja: '開発者とAPI',
    },
  },
  {
    key: 'kelvinseek',
    path: '/kelvinseek',
    keywords: ['bot', 'telegram', 'kelvin', 'assistant'],
    titles: same('KelvinSeek'),
  },
  {
    key: 'brand',
    path: '/brand',
    keywords: ['logo', 'press', 'brand'],
    titles: {
      en: 'Brand assets',
      es: 'Recursos de marca',
      de: 'Markenmaterial',
      fr: 'Ressources de marque',
      it: 'Risorse del marchio',
      nl: 'Merkmateriaal',
      pl: 'Materiały marki',
      pt: 'Recursos da marca',
      ru: 'Материалы бренда',
      sv: 'Varumärkesmaterial',
      tr: 'Marka varlıkları',
      zh: '品牌资源',
      ja: 'ブランド素材',
    },
  },
  {
    key: 'privacy',
    path: '/privacy',
    keywords: ['privacy', 'gdpr', 'data'],
    titles: {
      en: 'Privacy policy',
      es: 'Política de privacidad',
      de: 'Datenschutzerklärung',
      fr: 'Politique de confidentialité',
      it: 'Informativa sulla privacy',
      nl: 'Privacybeleid',
      pl: 'Polityka prywatności',
      pt: 'Política de privacidade',
      ru: 'Политика конфиденциальности',
      sv: 'Integritetspolicy',
      tr: 'Gizlilik politikası',
      zh: '隐私政策',
      ja: 'プライバシーポリシー',
    },
  },
  {
    key: 'terms',
    path: '/terms',
    keywords: ['terms', 'tos', 'rules'],
    titles: {
      en: 'Terms of service',
      es: 'Términos del servicio',
      de: 'Nutzungsbedingungen',
      fr: 'Conditions d’utilisation',
      it: 'Termini di servizio',
      nl: 'Servicevoorwaarden',
      pl: 'Regulamin',
      pt: 'Termos de serviço',
      ru: 'Условия использования',
      sv: 'Användarvillkor',
      tr: 'Hizmet şartları',
      zh: '服务条款',
      ja: '利用規約',
    },
  },
  {
    key: 'content-policy',
    path: '/content-policy',
    keywords: ['rules', 'nsfw', 'moderation', 'guidelines'],
    titles: {
      en: 'Content policy',
      es: 'Política de contenido',
      de: 'Inhaltsrichtlinie',
      fr: 'Politique de contenu',
      it: 'Norme sui contenuti',
      nl: 'Contentbeleid',
      pl: 'Zasady treści',
      pt: 'Política de conteúdo',
      ru: 'Правила публикации',
      sv: 'Innehållspolicy',
      tr: 'İçerik politikası',
      zh: '内容政策',
      ja: 'コンテンツポリシー',
    },
  },
  { key: 'dmca', path: '/dmca', keywords: ['copyright', 'takedown'], titles: same('DMCA') },
  {
    key: 'cookies',
    path: '/cookies',
    keywords: ['cookies', 'consent', 'tracking'],
    titles: {
      en: 'Cookie policy',
      es: 'Política de cookies',
      de: 'Cookie-Richtlinie',
      fr: 'Politique relative aux cookies',
      it: 'Informativa sui cookie',
      nl: 'Cookiebeleid',
      pl: 'Polityka plików cookie',
      pt: 'Política de cookies',
      ru: 'Политика cookie',
      sv: 'Cookiepolicy',
      tr: 'Çerez politikası',
      zh: 'Cookie 政策',
      ja: 'Cookieポリシー',
    },
  },
];
