/**
 * @sotf/db: Database layer (PLAN §6): Drizzle schema for the legacy and v2 tables, hand-written
 * additive SQL migrations, the migration runner, the legacy ⊆ v2 superset guard and test helpers.
 *
 * Skeleton created by WP-00; delivered by WP-10. The schema barrel `src/schema/_index.gen.ts` is
 * generated by `pnpm gen`.
 */
export {};
