/**
 * Generates `src/font-fallbacks.gen.css`: a metric-matched local fallback face for Onest, the
 * only web font, so swapping it in causes no layout shift (CLS 0).
 *
 * The overrides are computed by fontaine from the Fontsource woff2 files (never written by hand):
 * `size-adjust` matches the average character width, and the ascent/descent/line-gap overrides
 * reproduce the web font's vertical metrics on the local face.
 *
 *   node scripts/gen-font-fallbacks.ts          # write the file (also run by `pnpm gen`)
 *   node scripts/gen-font-fallbacks.ts --check  # exit 1 if the committed file is stale
 */
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { generateFontFace, getMetricsForFamily, readMetrics } from 'fontaine';

const require = createRequire(import.meta.url);
const OUTPUT = fileURLToPath(new URL('../src/font-fallbacks.gen.css', import.meta.url).href);

interface FallbackSpec {
  /** Family name referenced by the `--font-*` stacks of tokens.css. */
  name: string;
  /** Web font file whose metrics the fallback imitates (latin subset). */
  file: string;
  /** Local fonts tried in order; all share the metrics of `metricsFamily`. */
  locals: readonly string[];
  metricsFamily: 'Arial';
}

const SPECS: readonly FallbackSpec[] = [
  {
    name: 'Onest Fallback',
    file: '@fontsource-variable/onest/files/onest-latin-wght-normal.woff2',
    // Liberation Sans and Arimo are metric-compatible with Arial (Linux, ChromeOS).
    locals: ['Arial', 'ArialMT', 'Liberation Sans', 'Arimo'],
    metricsFamily: 'Arial',
  },
];

async function fallbackMetrics(family: FallbackSpec['metricsFamily']) {
  const metrics = await getMetricsForFamily(family);
  if (!metrics) throw new Error(`fontaine has no metrics for ${family}`);
  return metrics;
}

export async function renderFallbacks(): Promise<string> {
  const faces: string[] = [];
  for (const spec of SPECS) {
    const metrics = await readMetrics(pathToFileURL(require.resolve(spec.file)).href);
    if (!metrics) throw new Error(`could not read metrics from ${spec.file}`);
    const face = generateFontFace(metrics, {
      name: spec.name,
      font: spec.locals[0] ?? 'Arial',
      metrics: await fallbackMetrics(spec.metricsFamily),
    });
    // fontaine writes a single local(); list every metric-compatible local font instead.
    const src = spec.locals.map((local) => `local("${local}")`).join(', ');
    faces.push(face.trim().replace(/src: local\("[^"]*"\);/, `src: ${src};`));
  }
  return [
    '/* Generated by scripts/gen-font-fallbacks.ts (fontaine). Do not edit: run `pnpm --filter @sotf/ui gen`. */',
    ...faces,
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const css = await renderFallbacks();
  if (process.argv.includes('--check')) {
    const current = await readFile(OUTPUT, 'utf8').catch(() => '');
    if (current !== css) {
      process.stderr.write('src/font-fallbacks.gen.css is stale: run `pnpm --filter @sotf/ui gen`\n');
      process.exit(1);
    }
    return;
  }
  await writeFile(OUTPUT, css);
  process.stdout.write('wrote src/font-fallbacks.gen.css\n');
}

if (import.meta.main) await main();
