/**
 * Generates `src/generated/brand-data.gen.ts`: the Onest Bold outlines of A-Z and 0-9 for
 * font-independent initials (avatars, covers), so runtime code only concatenates strings, and the
 * wordmark PNG as base64 (OG images).
 *
 * The font is `sources/fonts/Onest-Bold-latin.ttf`, a static instance (wght 700) of the
 * Onest variable font (SIL OFL 1.1). The OFL allows embedding glyph outlines in artwork.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import opentype, { type Font, type Glyph, type Path } from 'opentype.js';
import { PathWriter } from '../../src/svg.ts';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

export const FONT_FILES = {
  display: join(ROOT, 'sources', 'fonts', 'Onest-Bold-latin.ttf'),
} as const;

/** All outlines are normalised so that the font's cap height equals this many units. */
export const CAP_UNITS = 100;

function loadFont(path: string): Font {
  const file = readFileSync(path);
  return opentype.parse(file.buffer.slice(file.byteOffset, file.byteOffset + file.byteLength));
}

interface SetText {
  readonly d: string;
  /** Pen advance including tracking after every glyph but the last. */
  readonly advance: number;
  /** Tight ink bounds (baseline at y = 0, caps reach y ≈ −100). */
  readonly x1: number;
  readonly x2: number;
  readonly y1: number;
  readonly y2: number;
}

function writePath(writer: PathWriter, path: Path): void {
  for (const command of path.commands) {
    switch (command.type) {
      case 'M':
        writer.moveTo(command.x as number, command.y as number);
        break;
      case 'L':
        writer.lineTo(command.x as number, command.y as number);
        break;
      case 'Q':
        writer.quadTo(command.x1 as number, command.y1 as number, command.x as number, command.y as number);
        break;
      case 'C':
        writer.cubicTo(
          command.x1 as number,
          command.y1 as number,
          command.x2 as number,
          command.y2 as number,
          command.x as number,
          command.y as number,
        );
        break;
      case 'Z':
        writer.close();
        break;
      default:
        throw new Error(`Unsupported path command ${(command as { type: string }).type}`);
    }
  }
}

function setText(font: Font, text: string, tracking = 0, precision = 1): SetText {
  const fontSize = (CAP_UNITS * font.unitsPerEm) / font.tables.os2.sCapHeight;
  const scale = fontSize / font.unitsPerEm;
  const writer = new PathWriter(precision);
  let x = 0;
  let x1 = Number.POSITIVE_INFINITY;
  let x2 = Number.NEGATIVE_INFINITY;
  let y1 = Number.POSITIVE_INFINITY;
  let y2 = Number.NEGATIVE_INFINITY;
  let previous: Glyph | null = null;
  const chars = [...text];
  chars.forEach((char, index) => {
    if (!font.hasChar(char)) {
      throw new Error(`Font has no glyph for "${char}"`);
    }
    const glyph = font.charToGlyph(char);
    if (previous) {
      x += font.getKerningValue(previous, glyph) * scale;
    }
    const path = glyph.getPath(x, 0, fontSize);
    if (path.commands.length > 0) {
      writePath(writer, path);
      const box = path.getBoundingBox();
      x1 = Math.min(x1, box.x1);
      x2 = Math.max(x2, box.x2);
      y1 = Math.min(y1, box.y1);
      y2 = Math.max(y2, box.y2);
    }
    x += (glyph.advanceWidth ?? 0) * scale + (index < chars.length - 1 ? tracking : 0);
    previous = glyph;
  });
  const round = (value: number): number => Math.round(value * 100) / 100;
  return { d: writer.toString(), advance: round(x), x1: round(x1), x2: round(x2), y1: round(y1), y2: round(y2) };
}

const INITIAL_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';

function literal(value: unknown): string {
  return JSON.stringify(value, null, 2).replace(/"([A-Za-z_][A-Za-z0-9_]*)":/g, '$1:');
}

/** Returns the TypeScript source of `src/generated/brand-data.gen.ts`. */
export function generateBrandDataSource(): string {
  const display = loadFont(FONT_FILES.display);
  const glyphs: Record<string, SetText> = {};
  for (const char of INITIAL_CHARS) {
    glyphs[char] = setText(display, char);
  }

  const header = [
    '// Generated by scripts/build-assets.ts (scripts/lib/sources.ts). Do not edit by hand.',
    '// Regenerate with `pnpm --filter @sotf/brand build:assets`.',
    '// Glyph outlines: Onest Bold (SIL OFL 1.1).',
    '',
    'export interface OutlinedText {',
    '  readonly d: string;',
    '  readonly advance: number;',
    '  readonly x1: number;',
    '  readonly x2: number;',
    '  readonly y1: number;',
    '  readonly y2: number;',
    '}',
    '',
  ].join('\n');

  const logo = readFileSync(join(ROOT, 'sources', 'logo-sm.png')).toString('base64');

  return `${header}
/** Units of cap height every outline below is normalised to. */
export const CAP_UNITS = ${CAP_UNITS};

/** Onest Bold capitals and digits for initials, baseline at y = 0. */
export const INITIAL_GLYPHS: Readonly<Record<string, OutlinedText>> = ${literal(glyphs)};

/** The one-line SOTF-MODS logo (\`sources/logo-sm.png\`, 419 x 110), base64, for renderers that cannot load files (OG images). */
export const LOGO_WORDMARK_PNG_BASE64 = '${logo}';
`;
}
