// Code generated by `pnpm gen` (tooling/scripts/gen-registries.ts). DO NOT EDIT.
// Regenerate after adding, removing or renaming an entry; on merge conflicts, regenerate.

import accountModule from './account/index.ts';
import authModule from './auth/index.ts';
import catalogModule from './catalog/index.ts';
import downloadsModule from './downloads/index.ts';
import eventsModule from './events/index.ts';
import followsModule from './follows/index.ts';
import kitsModule from './kits/index.ts';
import legacyModule from './legacy/index.ts';
import meModule from './me/index.ts';
import notificationsModule from './notifications/index.ts';
import platformModule from './platform/index.ts';
import resolveModule from './resolve/index.ts';
import searchModule from './search/index.ts';
import siteModule from './site/index.ts';
import studioAnalyticsModule from './studio-analytics/index.ts';
import unsubscribeModule from './unsubscribe/index.ts';
import uploadsModule from './uploads/index.ts';

export const modules = [
  accountModule,
  authModule,
  catalogModule,
  downloadsModule,
  eventsModule,
  followsModule,
  kitsModule,
  legacyModule,
  meModule,
  notificationsModule,
  platformModule,
  resolveModule,
  searchModule,
  siteModule,
  studioAnalyticsModule,
  unsubscribeModule,
  uploadsModule,
] as const;
