// Code generated by `pnpm gen` (tooling/scripts/gen-registries.ts). DO NOT EDIT.
// Regenerate after adding, removing or renaming an entry; on merge conflicts, regenerate.

import downloadsModule from './downloads/index.ts';
import platformModule from './platform/index.ts';
import resolveModule from './resolve/index.ts';
import uploadsModule from './uploads/index.ts';

export const modules = [
  downloadsModule,
  platformModule,
  resolveModule,
  uploadsModule,
] as const;
