// Code generated by `pnpm gen` (tooling/scripts/gen-registries.ts). DO NOT EDIT.
// Regenerate after adding, removing or renaming an entry; on merge conflicts, regenerate.

import platformModule from './platform/index.ts';

export const modules = [
  platformModule,
] as const;
