// Generated by packages/contracts/scripts/gen-legacy.ts from fixtures/legacy/ — DO NOT EDIT.
// Regenerate with `pnpm gen` (or `pnpm --filter @sotf/contracts gen`).
//
// 38 golden fixtures captured from api.sotf-mods.com on 2026-09-29 (research/01).
// Key order = declaration order; `assertKeyOrder` (legacy.ts) enforces it at runtime.

import { z } from 'zod';
import { dto } from './dto.ts';

/** `Date.prototype.toISOString()` output: milliseconds and `Z` (Prisma DateTime in UTC). */
export const LegacyDateTime = z.iso.datetime({ precision: 3 });
/** Calendar day `YYYY-MM-DD` (UTC). */
export const LegacyDate = z.iso.date();

/** Author embedded in mods and comments (`imageUrl` is "" without avatar). (125 sample(s) from mods-default, mods-redmanager-p1, mods-redmanager-unapproved, mods-redmanager-search, mods-updateschecker-modids, mods-updateschecker-page, mods-frontend-list, mods-type-build, mods-user, mod-by-id, mod-by-id-build, mod-by-slug, featured, builds-featured, comments) */
export const LegacyUserRef = dto(
  "LegacyUserRef",
  z.strictObject({
    name: z.string(),
    slug: z.string(),
    imageUrl: z.string(),
    isTrusted: z.boolean(),
  }),
  {
    description: "Author embedded in mods and comments (`imageUrl` is \"\" without avatar).",
    examples: [{
      "name": "AKM",
      "slug": "akm",
      "imageUrl": "https://r2.sotf-mods.com/1790458504827_3819_avatar.jpg",
      "isTrusted": false
    }],
  },
);
export type LegacyUserRef = z.infer<typeof LegacyUserRef>;

/** Category embedded in mods. (116 sample(s) from mods-default, mods-redmanager-p1, mods-redmanager-unapproved, mods-redmanager-search, mods-updateschecker-modids, mods-updateschecker-page, mods-frontend-list, mods-type-build, mods-user, mod-by-id, mod-by-id-build, mod-by-slug, featured, builds-featured) */
export const LegacyCategoryRef = dto(
  "LegacyCategoryRef",
  z.strictObject({
    name: z.string(),
    slug: z.string(),
  }),
  {
    description: "Category embedded in mods.",
    examples: [{
      "name": "Model Swap",
      "slug": "model-swap"
    }],
  },
);
export type LegacyCategoryRef = z.infer<typeof LegacyCategoryRef>;

/** Image of a mod in lists and featured endpoints. (108 sample(s) from mods-default, mods-redmanager-p1, mods-redmanager-unapproved, mods-redmanager-search, mods-updateschecker-page, mods-frontend-list, mods-type-build, featured) */
export const LegacyModListImage = dto(
  "LegacyModListImage",
  z.strictObject({
    isPrimary: z.boolean(),
    isThumbnail: z.boolean(),
    url: z.string(),
  }),
  {
    description: "Image of a mod in lists and featured endpoints.",
    examples: [{
      "isPrimary": false,
      "isThumbnail": false,
      "url": "https://r2.sotf-mods.com/1790458408884_af4.jpg"
    }],
  },
);
export type LegacyModListImage = z.infer<typeof LegacyModListImage>;

/** The single version embedded in list items: the lowest by ascending string order (preserved quirk). (97 sample(s) from mods-default, mods-redmanager-p1, mods-redmanager-unapproved, mods-redmanager-search, mods-updateschecker-modids, mods-updateschecker-page, mods-frontend-list, mods-type-build, mods-user) */
export const LegacyModListVersion = dto(
  "LegacyModListVersion",
  z.strictObject({
    version: z.string(),
    isLatest: z.boolean(),
  }),
  {
    description: "The single version embedded in list items: the lowest by ascending string order (preserved quirk).",
    examples: [{
      "version": "1.0.0",
      "isLatest": true
    }],
  },
);
export type LegacyModListVersion = z.infer<typeof LegacyModListVersion>;

/** `_count` of a mod. (104 sample(s) from mods-default, mods-redmanager-p1, mods-redmanager-unapproved, mods-redmanager-search, mods-updateschecker-modids, mods-updateschecker-page, mods-frontend-list, mods-type-build, mods-user, mod-by-id, mod-by-id-build, mod-by-slug, builds-featured) */
export const LegacyFavoritesCount = dto(
  "LegacyFavoritesCount",
  z.strictObject({
    favorites: z.number().int(),
  }),
  {
    description: "`_count` of a mod.",
    examples: [{
      "favorites": 0
    }],
  },
);
export type LegacyFavoritesCount = z.infer<typeof LegacyFavoritesCount>;

/** Pagination of `GET /api/mods`: pages = ceil(total/limit), next_page = min(page+1, pages), prev_page = max(page-1, 1). (10 sample(s) from mods-default, mods-redmanager-p1, mods-redmanager-unapproved, mods-redmanager-search, mods-updateschecker-modids, mods-updateschecker-page, mods-frontend-list, mods-type-build, mods-user, mods-limit0) */
export const LegacyListMeta = dto(
  "LegacyListMeta",
  z.strictObject({
    total: z.number().int(),
    page: z.number().int(),
    limit: z.number().int(),
    pages: z.number().int().nullable(),
    next_page: z.number().int(),
    prev_page: z.number().int(),
  }),
  {
    description: "Pagination of `GET /api/mods`: pages = ceil(total/limit), next_page = min(page+1, pages), prev_page = max(page-1, 1).",
    examples: [{
      "total": 195,
      "page": 1,
      "limit": 10,
      "pages": 20,
      "next_page": 2,
      "prev_page": 1
    }],
  },
);
export type LegacyListMeta = z.infer<typeof LegacyListMeta>;

/** Item of `GET /api/mods` (UpdatesChecker, RedManager): Mod scalars in legacy order + images, user, category, versions (1) and _count. `dependencies` is an array here. (97 sample(s) from mods-default, mods-redmanager-p1, mods-redmanager-unapproved, mods-redmanager-search, mods-updateschecker-modids, mods-updateschecker-page, mods-frontend-list, mods-type-build, mods-user) */
export const LegacyModListItem = dto(
  "LegacyModListItem",
  z.strictObject({
    id: z.number().int(),
    name: z.string(),
    slug: z.string(),
    mod_id: z.string(),
    shortDescription: z.string(),
    description: z.string(),
    dependencies: z.array(z.string()),
    type: z.string().nullable(),
    modSide: z.string().nullable(),
    isNSFW: z.boolean(),
    isApproved: z.boolean(),
    isFeatured: z.boolean(),
    isMultiplayerCompatible: z.boolean(),
    requiresAllPlayers: z.boolean(),
    lastWeekDownloads: z.number().int(),
    downloads: z.number().int(),
    latestVersion: z.string().nullable(),
    latestVersionSize: z.string().nullable(),
    averageRating: z.number(),
    reviewsCount: z.number().int(),
    favoritesCount: z.number().int(),
    commentsCount: z.number().int(),
    sourceUrl: z.string().nullable(),
    imageUrl: z.string().nullable(),
    buildGuid: z.string().nullable(),
    buildShareVersion: z.string().nullable(),
    numberOfElements: z.number().int().nullable(),
    lastReleasedAt: LegacyDateTime,
    createdAt: LegacyDateTime,
    updatedAt: LegacyDateTime,
    userId: z.number().int(),
    categoryId: z.number().int(),
    images: z.array(LegacyModListImage),
    user: LegacyUserRef,
    category: LegacyCategoryRef.nullable(),
    versions: z.array(LegacyModListVersion),
    _count: LegacyFavoritesCount,
  }),
  {
    description: "Item of `GET /api/mods` (UpdatesChecker, RedManager): Mod scalars in legacy order + images, user, category, versions (1) and _count. `dependencies` is an array here.",
    examples: [{
      "id": 320,
      "name": "Arctic Fox Virginia",
      "slug": "arctic-fox-virginia",
      "mod_id": "ArcticVirginia",
      "shortDescription": "Turns Virginia into a pagan arctic fox lady.",
      "description": "Changes Virginia into an anthropomorphic / furry arctic fox, because\n\n1. Humans are stinky and ugly!\n2. Arctic foxes come from hyperborea and are therefore kino.\n\nWalking animations may look a bit ...",
      "dependencies": [],
      "type": "Mod",
      "modSide": "client",
      "isNSFW": false,
      "isApproved": true,
      "isFeatured": false,
      "isMultiplayerCompatible": false,
      "requiresAllPlayers": false,
      "lastWeekDownloads": 70,
      "downloads": 70,
      "latestVersion": "1.0.0",
      "latestVersionSize": "",
      "averageRating": 0,
      "reviewsCount": 0,
      "favoritesCount": 0,
      "commentsCount": 0,
      "sourceUrl": null,
      "imageUrl": "https://r2.sotf-mods.com/1790458408372_arctic fox savage.png",
      "buildGuid": null,
      "buildShareVersion": null,
      "numberOfElements": null,
      "lastReleasedAt": "2026-09-26T21:33:31.396Z",
      "createdAt": "2026-09-26T21:33:31.396Z",
      "updatedAt": "2026-09-29T04:00:00.703Z",
      "userId": 3819,
      "categoryId": 2,
      "images": [
        {
          "isPrimary": false,
          "isThumbnail": false,
          "url": "https://r2.sotf-mods.com/1790458408884_af4.jpg"
        }
      ],
      "user": {
        "name": "AKM",
        "slug": "akm",
        "imageUrl": "https://r2.sotf-mods.com/1790458504827_3819_avatar.jpg",
        "isTrusted": false
      },
      "category": {
        "name": "Model Swap",
        "slug": "model-swap"
      },
      "versions": [
        {
          "version": "1.0.0",
          "isLatest": true
        }
      ],
      "_count": {
        "favorites": 0
      }
    }],
  },
);
export type LegacyModListItem = z.infer<typeof LegacyModListItem>;

/** Envelope of `GET /api/mods`. (10 sample(s) from mods-default, mods-redmanager-p1, mods-redmanager-unapproved, mods-redmanager-search, mods-updateschecker-modids, mods-updateschecker-page, mods-frontend-list, mods-type-build, mods-user, mods-limit0) */
export const LegacyModListResponse = dto(
  "LegacyModListResponse",
  z.strictObject({
    status: z.literal(true),
    data: z.array(LegacyModListItem),
    meta: LegacyListMeta,
  }),
  {
    description: "Envelope of `GET /api/mods`.",
    examples: [{
      "status": true,
      "data": [
        {
          "id": 320,
          "name": "Arctic Fox Virginia",
          "slug": "arctic-fox-virginia",
          "mod_id": "ArcticVirginia",
          "shortDescription": "Turns Virginia into a pagan arctic fox lady.",
          "description": "Changes Virginia into an anthropomorphic / furry arctic fox, because\n\n1. Humans are stinky and ugly!\n2. Arctic foxes come from hyperborea and are therefore kino.\n\nWalking animations may look a bit ...",
          "dependencies": [],
          "type": "Mod",
          "modSide": "client",
          "isNSFW": false,
          "isApproved": true,
          "isFeatured": false,
          "isMultiplayerCompatible": false,
          "requiresAllPlayers": false,
          "lastWeekDownloads": 70,
          "downloads": 70,
          "latestVersion": "1.0.0",
          "latestVersionSize": "",
          "averageRating": 0,
          "reviewsCount": 0,
          "favoritesCount": 0,
          "commentsCount": 0,
          "sourceUrl": null,
          "imageUrl": "https://r2.sotf-mods.com/1790458408372_arctic fox savage.png",
          "buildGuid": null,
          "buildShareVersion": null,
          "numberOfElements": null,
          "lastReleasedAt": "2026-09-26T21:33:31.396Z",
          "createdAt": "2026-09-26T21:33:31.396Z",
          "updatedAt": "2026-09-29T04:00:00.703Z",
          "userId": 3819,
          "categoryId": 2,
          "images": [
            {
              "isPrimary": false,
              "isThumbnail": false,
              "url": "https://r2.sotf-mods.com/1790458408884_af4.jpg"
            }
          ],
          "user": {
            "name": "AKM",
            "slug": "akm",
            "imageUrl": "https://r2.sotf-mods.com/1790458504827_3819_avatar.jpg",
            "isTrusted": false
          },
          "category": {
            "name": "Model Swap",
            "slug": "model-swap"
          },
          "versions": [
            {
              "version": "1.0.0",
              "isLatest": true
            }
          ],
          "_count": {
            "favorites": 0
          }
        }
      ],
      "meta": {
        "total": 195,
        "page": 1,
        "limit": 10,
        "pages": 20,
        "next_page": 2,
        "prev_page": 1
      }
    }],
  },
);
export type LegacyModListResponse = z.infer<typeof LegacyModListResponse>;

/** Image of the detail endpoint (only `url`; the captured mods have no gallery). (no samples in the fixtures (declared in legacy-spec.ts)) */
export const LegacyModDetailImage = dto(
  "LegacyModDetailImage",
  z.strictObject({
    url: z.string(),
  }),
  {
    description: "Image of the detail endpoint (only `url`; the captured mods have no gallery).",
    examples: [{
      "url": "https://r2.sotf-mods.com/1767666009017_axel's-mod-menu_1.png"
    }],
  },
);
export type LegacyModDetailImage = z.infer<typeof LegacyModDetailImage>;

/** `_count` of a version. (41 sample(s) from mod-by-id, mod-by-id-build, mod-by-slug) */
export const LegacyDownloadsCount = dto(
  "LegacyDownloadsCount",
  z.strictObject({
    downloads: z.number().int(),
  }),
  {
    description: "`_count` of a version.",
    examples: [{
      "downloads": 19160
    }],
  },
);
export type LegacyDownloadsCount = z.infer<typeof LegacyDownloadsCount>;

/** Version in the detail endpoint (all versions, string order desc; `downloadUrl` is the raw, unencoded URL). (41 sample(s) from mod-by-id, mod-by-id-build, mod-by-slug) */
export const LegacyModDetailVersion = dto(
  "LegacyModDetailVersion",
  z.strictObject({
    id: z.number().int(),
    version: z.string(),
    isLatest: z.boolean(),
    changelog: z.string(),
    downloadUrl: z.string(),
    extension: z.string().nullable(),
    filename: z.string().nullable(),
    createdAt: LegacyDateTime,
    updatedAt: LegacyDateTime,
    _count: LegacyDownloadsCount,
  }),
  {
    description: "Version in the detail endpoint (all versions, string order desc; `downloadUrl` is the raw, unencoded URL).",
    examples: [{
      "id": 664,
      "version": "1.3.8",
      "isLatest": true,
      "changelog": "Fixed noclip causing issues with riding ziplines and character physics override",
      "downloadUrl": "https://r2.sotf-mods.com/1775413983720_axel's-mod-menu_1.3.8.zip",
      "extension": "zip",
      "filename": "1775413983720_axel's-mod-menu_1.3.8.zip",
      "createdAt": "2026-04-05T18:33:04.943Z",
      "updatedAt": "2026-04-05T18:33:04.943Z",
      "_count": {
        "downloads": 19160
      }
    }],
  },
);
export type LegacyModDetailVersion = z.infer<typeof LegacyModDetailVersion>;

/** `GET /api/mods/:mod_id` and `/api/mods/slug/:u/:s`: same scalars as the list but `dependencies` is the raw string. (3 sample(s) from mod-by-id, mod-by-id-build, mod-by-slug) */
export const LegacyModDetail = dto(
  "LegacyModDetail",
  z.strictObject({
    id: z.number().int(),
    name: z.string(),
    slug: z.string(),
    mod_id: z.string(),
    shortDescription: z.string(),
    description: z.string(),
    dependencies: z.string(),
    type: z.string().nullable(),
    modSide: z.string().nullable(),
    isNSFW: z.boolean(),
    isApproved: z.boolean(),
    isFeatured: z.boolean(),
    isMultiplayerCompatible: z.boolean(),
    requiresAllPlayers: z.boolean(),
    lastWeekDownloads: z.number().int(),
    downloads: z.number().int(),
    latestVersion: z.string().nullable(),
    latestVersionSize: z.string().nullable(),
    averageRating: z.number(),
    reviewsCount: z.number().int(),
    favoritesCount: z.number().int(),
    commentsCount: z.number().int(),
    sourceUrl: z.string().nullable(),
    imageUrl: z.string().nullable(),
    buildGuid: z.string().nullable(),
    buildShareVersion: z.string().nullable(),
    numberOfElements: z.number().int().nullable(),
    lastReleasedAt: LegacyDateTime,
    createdAt: LegacyDateTime,
    updatedAt: LegacyDateTime,
    userId: z.number().int(),
    categoryId: z.number().int(),
    images: z.array(LegacyModDetailImage),
    user: LegacyUserRef,
    category: LegacyCategoryRef.nullable(),
    versions: z.array(LegacyModDetailVersion),
    _count: LegacyFavoritesCount,
  }),
  {
    description: "`GET /api/mods/:mod_id` and `/api/mods/slug/:u/:s`: same scalars as the list but `dependencies` is the raw string.",
    examples: [{
      "id": 20,
      "name": "Axel's Mod Menu",
      "slug": "axel's-mod-menu",
      "mod_id": "AxelModMenu",
      "shortDescription": "Featurefull mod menu for Sons of The Forest",
      "description": "# <FONT COLOR=\"#ffff4d\">Warning</FONT COLOR>\r\nNeeds my `SonsAxLib v1.2.0+` library to work, download it here: https://sotf-mods.com/mods/imaxel/sonsaxlib\r\n\r\n### How to use\r\nDefault opening key is i...",
      "dependencies": "SonsAxLib",
      "type": "Mod",
      "modSide": null,
      "isNSFW": false,
      "isApproved": true,
      "isFeatured": false,
      "isMultiplayerCompatible": false,
      "requiresAllPlayers": false,
      "lastWeekDownloads": 511,
      "downloads": 117719,
      "latestVersion": "1.3.8",
      "latestVersionSize": "",
      "averageRating": 0,
      "reviewsCount": 0,
      "favoritesCount": 7,
      "commentsCount": 9,
      "sourceUrl": null,
      "imageUrl": "https://r2.sotf-mods.com/1767665951899_1696956193461_axel's-mod-menu_thumbnail.png",
      "buildGuid": null,
      "buildShareVersion": null,
      "numberOfElements": null,
      "lastReleasedAt": "2026-04-05T18:33:04.942Z",
      "createdAt": "2023-10-10T16:43:13.458Z",
      "updatedAt": "2026-09-29T04:00:03.394Z",
      "userId": 4,
      "categoryId": 1,
      "images": [],
      "user": {
        "name": "ImAxel",
        "slug": "imaxel",
        "imageUrl": "",
        "isTrusted": true
      },
      "category": {
        "name": "Misc",
        "slug": "misc"
      },
      "versions": [
        {
          "id": 664,
          "version": "1.3.8",
          "isLatest": true,
          "changelog": "Fixed noclip causing issues with riding ziplines and character physics override",
          "downloadUrl": "https://r2.sotf-mods.com/1775413983720_axel's-mod-menu_1.3.8.zip",
          "extension": "zip",
          "filename": "1775413983720_axel's-mod-menu_1.3.8.zip",
          "createdAt": "2026-04-05T18:33:04.943Z",
          "updatedAt": "2026-04-05T18:33:04.943Z",
          "_count": {
            "downloads": 19160
          }
        }
      ],
      "_count": {
        "favorites": 7
      }
    }],
  },
);
export type LegacyModDetail = z.infer<typeof LegacyModDetail>;

/** Envelope of the mod detail. (3 sample(s) from mod-by-id, mod-by-id-build, mod-by-slug) */
export const LegacyModDetailResponse = dto(
  "LegacyModDetailResponse",
  z.strictObject({
    status: z.literal(true),
    data: LegacyModDetail,
  }),
  {
    description: "Envelope of the mod detail.",
    examples: [{
      "status": true,
      "data": {
        "id": 20,
        "name": "Axel's Mod Menu",
        "slug": "axel's-mod-menu",
        "mod_id": "AxelModMenu",
        "shortDescription": "Featurefull mod menu for Sons of The Forest",
        "description": "# <FONT COLOR=\"#ffff4d\">Warning</FONT COLOR>\r\nNeeds my `SonsAxLib v1.2.0+` library to work, download it here: https://sotf-mods.com/mods/imaxel/sonsaxlib\r\n\r\n### How to use\r\nDefault opening key is i...",
        "dependencies": "SonsAxLib",
        "type": "Mod",
        "modSide": null,
        "isNSFW": false,
        "isApproved": true,
        "isFeatured": false,
        "isMultiplayerCompatible": false,
        "requiresAllPlayers": false,
        "lastWeekDownloads": 511,
        "downloads": 117719,
        "latestVersion": "1.3.8",
        "latestVersionSize": "",
        "averageRating": 0,
        "reviewsCount": 0,
        "favoritesCount": 7,
        "commentsCount": 9,
        "sourceUrl": null,
        "imageUrl": "https://r2.sotf-mods.com/1767665951899_1696956193461_axel's-mod-menu_thumbnail.png",
        "buildGuid": null,
        "buildShareVersion": null,
        "numberOfElements": null,
        "lastReleasedAt": "2026-04-05T18:33:04.942Z",
        "createdAt": "2023-10-10T16:43:13.458Z",
        "updatedAt": "2026-09-29T04:00:03.394Z",
        "userId": 4,
        "categoryId": 1,
        "images": [],
        "user": {
          "name": "ImAxel",
          "slug": "imaxel",
          "imageUrl": "",
          "isTrusted": true
        },
        "category": {
          "name": "Misc",
          "slug": "misc"
        },
        "versions": [
          {
            "id": 664,
            "version": "1.3.8",
            "isLatest": true,
            "changelog": "Fixed noclip causing issues with riding ziplines and character physics override",
            "downloadUrl": "https://r2.sotf-mods.com/1775413983720_axel's-mod-menu_1.3.8.zip",
            "extension": "zip",
            "filename": "1775413983720_axel's-mod-menu_1.3.8.zip",
            "createdAt": "2026-04-05T18:33:04.943Z",
            "updatedAt": "2026-04-05T18:33:04.943Z",
            "_count": {
              "downloads": 19160
            }
          }
        ],
        "_count": {
          "favorites": 7
        }
      }
    }],
  },
);
export type LegacyModDetailResponse = z.infer<typeof LegacyModDetailResponse>;

/** Item of `GET /api/mods/featured` (12 mods; `dependencies` as string). (12 sample(s) from featured) */
export const LegacyFeaturedMod = dto(
  "LegacyFeaturedMod",
  z.strictObject({
    id: z.number().int(),
    name: z.string(),
    slug: z.string(),
    mod_id: z.string(),
    shortDescription: z.string(),
    isNSFW: z.boolean(),
    isApproved: z.boolean(),
    isFeatured: z.boolean(),
    lastReleasedAt: LegacyDateTime,
    type: z.string().nullable(),
    dependencies: z.string(),
    lastWeekDownloads: z.number().int(),
    imageUrl: z.string().nullable(),
    downloads: z.number().int(),
    favoritesCount: z.number().int(),
    latestVersion: z.string().nullable(),
    category: LegacyCategoryRef.nullable(),
    user: LegacyUserRef,
    images: z.array(LegacyModListImage),
  }),
  {
    description: "Item of `GET /api/mods/featured` (12 mods; `dependencies` as string).",
    examples: [{
      "id": 20,
      "name": "Axel's Mod Menu",
      "slug": "axel's-mod-menu",
      "mod_id": "AxelModMenu",
      "shortDescription": "Featurefull mod menu for Sons of The Forest",
      "isNSFW": false,
      "isApproved": true,
      "isFeatured": false,
      "lastReleasedAt": "2026-04-05T18:33:04.942Z",
      "type": "Mod",
      "dependencies": "SonsAxLib",
      "lastWeekDownloads": 511,
      "imageUrl": "https://r2.sotf-mods.com/1767665951899_1696956193461_axel's-mod-menu_thumbnail.png",
      "downloads": 117719,
      "favoritesCount": 7,
      "latestVersion": "1.3.8",
      "category": {
        "name": "Misc",
        "slug": "misc"
      },
      "user": {
        "name": "ImAxel",
        "slug": "imaxel",
        "imageUrl": "",
        "isTrusted": true
      },
      "images": []
    }],
  },
);
export type LegacyFeaturedMod = z.infer<typeof LegacyFeaturedMod>;

/** Envelope of `GET /api/mods/featured`. (1 sample(s) from featured) */
export const LegacyFeaturedModsResponse = dto(
  "LegacyFeaturedModsResponse",
  z.strictObject({
    status: z.literal(true),
    data: z.array(LegacyFeaturedMod),
  }),
  {
    description: "Envelope of `GET /api/mods/featured`.",
    examples: [{
      "status": true,
      "data": [
        {
          "id": 20,
          "name": "Axel's Mod Menu",
          "slug": "axel's-mod-menu",
          "mod_id": "AxelModMenu",
          "shortDescription": "Featurefull mod menu for Sons of The Forest",
          "isNSFW": false,
          "isApproved": true,
          "isFeatured": false,
          "lastReleasedAt": "2026-04-05T18:33:04.942Z",
          "type": "Mod",
          "dependencies": "SonsAxLib",
          "lastWeekDownloads": 511,
          "imageUrl": "https://r2.sotf-mods.com/1767665951899_1696956193461_axel's-mod-menu_thumbnail.png",
          "downloads": 117719,
          "favoritesCount": 7,
          "latestVersion": "1.3.8",
          "category": {
            "name": "Misc",
            "slug": "misc"
          },
          "user": {
            "name": "ImAxel",
            "slug": "imaxel",
            "imageUrl": "",
            "isTrusted": true
          },
          "images": []
        }
      ]
    }],
  },
);
export type LegacyFeaturedModsResponse = z.infer<typeof LegacyFeaturedModsResponse>;

/** Item of `GET /api/builds/featured` (4 builds; no `favoritesCount`, has `_count`). (4 sample(s) from builds-featured) */
export const LegacyFeaturedBuild = dto(
  "LegacyFeaturedBuild",
  z.strictObject({
    id: z.number().int(),
    name: z.string(),
    slug: z.string(),
    mod_id: z.string(),
    shortDescription: z.string(),
    isNSFW: z.boolean(),
    isApproved: z.boolean(),
    isFeatured: z.boolean(),
    lastReleasedAt: LegacyDateTime,
    type: z.string().nullable(),
    dependencies: z.string(),
    lastWeekDownloads: z.number().int(),
    imageUrl: z.string().nullable(),
    downloads: z.number().int(),
    latestVersion: z.string().nullable(),
    category: LegacyCategoryRef.nullable(),
    user: LegacyUserRef,
    images: z.array(LegacyModListImage),
    _count: LegacyFavoritesCount,
  }),
  {
    description: "Item of `GET /api/builds/featured` (4 builds; no `favoritesCount`, has `_count`).",
    examples: [{
      "id": 265,
      "name": "MountianHouse",
      "slug": "mountianhouse",
      "mod_id": "e215ede2e4d742398c72aaca62496c10",
      "shortDescription": "My Description",
      "isNSFW": false,
      "isApproved": true,
      "isFeatured": false,
      "lastReleasedAt": "2025-11-10T13:24:45.847Z",
      "type": "Build",
      "dependencies": "",
      "lastWeekDownloads": 38,
      "imageUrl": "https://r2.sotf-mods.com/1767666009017_1762781085717_mountianhouse_thumbnail.jpg",
      "downloads": 2660,
      "latestVersion": "019a6df0-c08d-7000-a463-e838a2879469",
      "category": {
        "name": "Mountain Bases",
        "slug": "mountain-bases"
      },
      "user": {
        "name": "SzalonaKobita",
        "slug": "szalonakobita",
        "imageUrl": "",
        "isTrusted": false
      },
      "images": [],
      "_count": {
        "favorites": 1
      }
    }],
  },
);
export type LegacyFeaturedBuild = z.infer<typeof LegacyFeaturedBuild>;

/** Envelope of `GET /api/builds/featured`. (1 sample(s) from builds-featured) */
export const LegacyFeaturedBuildsResponse = dto(
  "LegacyFeaturedBuildsResponse",
  z.strictObject({
    status: z.literal(true),
    data: z.array(LegacyFeaturedBuild),
  }),
  {
    description: "Envelope of `GET /api/builds/featured`.",
    examples: [{
      "status": true,
      "data": [
        {
          "id": 265,
          "name": "MountianHouse",
          "slug": "mountianhouse",
          "mod_id": "e215ede2e4d742398c72aaca62496c10",
          "shortDescription": "My Description",
          "isNSFW": false,
          "isApproved": true,
          "isFeatured": false,
          "lastReleasedAt": "2025-11-10T13:24:45.847Z",
          "type": "Build",
          "dependencies": "",
          "lastWeekDownloads": 38,
          "imageUrl": "https://r2.sotf-mods.com/1767666009017_1762781085717_mountianhouse_thumbnail.jpg",
          "downloads": 2660,
          "latestVersion": "019a6df0-c08d-7000-a463-e838a2879469",
          "category": {
            "name": "Mountain Bases",
            "slug": "mountain-bases"
          },
          "user": {
            "name": "SzalonaKobita",
            "slug": "szalonakobita",
            "imageUrl": "",
            "isTrusted": false
          },
          "images": [],
          "_count": {
            "favorites": 1
          }
        }
      ]
    }],
  },
);
export type LegacyFeaturedBuildsResponse = z.infer<typeof LegacyFeaturedBuildsResponse>;

/** `GET /api/stats` and `/api/stats/builds` (downloads include the orphan rows). (2 sample(s) from stats, stats-builds) */
export const LegacyStats = dto(
  "LegacyStats",
  z.strictObject({
    users: z.number().int(),
    mods: z.number().int(),
    downloads: z.number().int(),
    developers: z.number().int(),
  }),
  {
    description: "`GET /api/stats` and `/api/stats/builds` (downloads include the orphan rows).",
    examples: [{
      "users": 3883,
      "mods": 257,
      "downloads": 1977061,
      "developers": 46
    }],
  },
);
export type LegacyStats = z.infer<typeof LegacyStats>;

/** Envelope of the stats endpoints. (2 sample(s) from stats, stats-builds) */
export const LegacyStatsResponse = dto(
  "LegacyStatsResponse",
  z.strictObject({
    status: z.literal(true),
    data: LegacyStats,
  }),
  {
    description: "Envelope of the stats endpoints.",
    examples: [{
      "status": true,
      "data": {
        "users": 3883,
        "mods": 257,
        "downloads": 1977061,
        "developers": 46
      }
    }],
  },
);
export type LegacyStatsResponse = z.infer<typeof LegacyStatsResponse>;

/** Item of `GET /api/categories` (ordered by name). (25 sample(s) from categories, categories-build) */
export const LegacyCategory = dto(
  "LegacyCategory",
  z.strictObject({
    id: z.number().int(),
    name: z.string(),
    slug: z.string(),
  }),
  {
    description: "Item of `GET /api/categories` (ordered by name).",
    examples: [{
      "id": 4,
      "name": "Library",
      "slug": "library"
    }],
  },
);
export type LegacyCategory = z.infer<typeof LegacyCategory>;

/** Envelope of `GET /api/categories`. (2 sample(s) from categories, categories-build) */
export const LegacyCategoriesResponse = dto(
  "LegacyCategoriesResponse",
  z.strictObject({
    status: z.literal(true),
    data: z.array(LegacyCategory),
  }),
  {
    description: "Envelope of `GET /api/categories`.",
    examples: [{
      "status": true,
      "data": [
        {
          "id": 4,
          "name": "Library",
          "slug": "library"
        }
      ]
    }],
  },
);
export type LegacyCategoriesResponse = z.infer<typeof LegacyCategoriesResponse>;

/** `GET /api/users/:slug`. (1 sample(s) from user) */
export const LegacyUser = dto(
  "LegacyUser",
  z.strictObject({
    name: z.string(),
    slug: z.string(),
    imageUrl: z.string(),
    isTrusted: z.boolean(),
    createdAt: LegacyDateTime,
  }),
  {
    description: "`GET /api/users/:slug`.",
    examples: [{
      "name": "ImAxel",
      "slug": "imaxel",
      "imageUrl": "",
      "isTrusted": true,
      "createdAt": "2023-09-22T06:13:49.867Z"
    }],
  },
);
export type LegacyUser = z.infer<typeof LegacyUser>;

/** Envelope of the user endpoint. (1 sample(s) from user) */
export const LegacyUserResponse = dto(
  "LegacyUserResponse",
  z.strictObject({
    status: z.literal(true),
    data: LegacyUser,
  }),
  {
    description: "Envelope of the user endpoint.",
    examples: [{
      "status": true,
      "data": {
        "name": "ImAxel",
        "slug": "imaxel",
        "imageUrl": "",
        "isTrusted": true,
        "createdAt": "2023-09-22T06:13:49.867Z"
      }
    }],
  },
);
export type LegacyUserResponse = z.infer<typeof LegacyUserResponse>;

/** `GET /api/users/:slug/stats`. (1 sample(s) from user-stats) */
export const LegacyUserStats = dto(
  "LegacyUserStats",
  z.strictObject({
    modsCount: z.number().int(),
    totalDownloads: z.number().int(),
    downloadsLastDay: z.number().int(),
    downloadsLast7Days: z.number().int(),
    downloadsLast30Days: z.number().int(),
    totalFavorites: z.number().int(),
    totalReviews: z.number().int(),
    averageRating: z.number(),
  }),
  {
    description: "`GET /api/users/:slug/stats`.",
    examples: [{
      "modsCount": 16,
      "totalDownloads": 374864,
      "downloadsLastDay": 203,
      "downloadsLast7Days": 1542,
      "downloadsLast30Days": 8001,
      "totalFavorites": 24,
      "totalReviews": 0,
      "averageRating": 0
    }],
  },
);
export type LegacyUserStats = z.infer<typeof LegacyUserStats>;

/** Envelope of the user stats endpoint. (1 sample(s) from user-stats) */
export const LegacyUserStatsResponse = dto(
  "LegacyUserStatsResponse",
  z.strictObject({
    status: z.literal(true),
    data: LegacyUserStats,
  }),
  {
    description: "Envelope of the user stats endpoint.",
    examples: [{
      "status": true,
      "data": {
        "modsCount": 16,
        "totalDownloads": 374864,
        "downloadsLastDay": 203,
        "downloadsLast7Days": 1542,
        "downloadsLast30Days": 8001,
        "totalFavorites": 24,
        "totalReviews": 0,
        "averageRating": 0
      }
    }],
  },
);
export type LegacyUserStatsResponse = z.infer<typeof LegacyUserStatsResponse>;

/** Reply of a legacy comment (same fields without `replies`; no captured comment has replies). (no samples in the fixtures (declared in legacy-spec.ts)) */
export const LegacyCommentReply = dto(
  "LegacyCommentReply",
  z.strictObject({
    id: z.number().int(),
    message: z.string(),
    imageUrl: z.string().nullable(),
    createdAt: LegacyDateTime,
    isHidden: z.boolean(),
    user: LegacyUserRef.nullable(),
  }),
  {
    description: "Reply of a legacy comment (same fields without `replies`; no captured comment has replies).",
    examples: [{
      "id": 221,
      "message": "I installed it through RedManager, entered the game, and nothing activates. I press the key, and nothing happens.",
      "imageUrl": null,
      "createdAt": "2026-05-07T14:45:18.805Z",
      "isHidden": false,
      "user": {
        "name": "euribeiiro",
        "slug": "euribeiiro",
        "imageUrl": "",
        "isTrusted": false
      }
    }],
  },
);
export type LegacyCommentReply = z.infer<typeof LegacyCommentReply>;

/** Top-level comment of `GET /api/comments?mod_id=` (newest first; replies oldest first). (9 sample(s) from comments) */
export const LegacyComment = dto(
  "LegacyComment",
  z.strictObject({
    id: z.number().int(),
    message: z.string(),
    imageUrl: z.string().nullable(),
    createdAt: LegacyDateTime,
    isHidden: z.boolean(),
    user: LegacyUserRef.nullable(),
    replies: z.array(LegacyCommentReply),
  }),
  {
    description: "Top-level comment of `GET /api/comments?mod_id=` (newest first; replies oldest first).",
    examples: [{
      "id": 221,
      "message": "I installed it through RedManager, entered the game, and nothing activates. I press the key, and nothing happens.",
      "imageUrl": null,
      "createdAt": "2026-05-07T14:45:18.805Z",
      "isHidden": false,
      "user": {
        "name": "euribeiiro",
        "slug": "euribeiiro",
        "imageUrl": "",
        "isTrusted": false
      },
      "replies": []
    }],
  },
);
export type LegacyComment = z.infer<typeof LegacyComment>;

/** Envelope of `GET /api/comments`. (1 sample(s) from comments) */
export const LegacyCommentsResponse = dto(
  "LegacyCommentsResponse",
  z.strictObject({
    status: z.literal(true),
    data: z.array(LegacyComment),
  }),
  {
    description: "Envelope of `GET /api/comments`.",
    examples: [{
      "status": true,
      "data": [
        {
          "id": 221,
          "message": "I installed it through RedManager, entered the game, and nothing activates. I press the key, and nothing happens.",
          "imageUrl": null,
          "createdAt": "2026-05-07T14:45:18.805Z",
          "isHidden": false,
          "user": {
            "name": "euribeiiro",
            "slug": "euribeiiro",
            "imageUrl": "",
            "isTrusted": false
          },
          "replies": []
        }
      ]
    }],
  },
);
export type LegacyCommentsResponse = z.infer<typeof LegacyCommentsResponse>;

/** Day of `GET /api/mods/:mod_id/download-stats` (only days with downloads, UTC). (8 sample(s) from download-stats-week) */
export const LegacyDownloadStat = dto(
  "LegacyDownloadStat",
  z.strictObject({
    date: LegacyDate,
    count: z.number().int(),
  }),
  {
    description: "Day of `GET /api/mods/:mod_id/download-stats` (only days with downloads, UTC).",
    examples: [{
      "date": "2026-09-22",
      "count": 54
    }],
  },
);
export type LegacyDownloadStat = z.infer<typeof LegacyDownloadStat>;

/** Envelope of the download stats endpoint. (1 sample(s) from download-stats-week) */
export const LegacyDownloadStatsResponse = dto(
  "LegacyDownloadStatsResponse",
  z.strictObject({
    status: z.literal(true),
    data: z.array(LegacyDownloadStat),
  }),
  {
    description: "Envelope of the download stats endpoint.",
    examples: [{
      "status": true,
      "data": [
        {
          "date": "2026-09-22",
          "count": 54
        }
      ]
    }],
  },
);
export type LegacyDownloadStatsResponse = z.infer<typeof LegacyDownloadStatsResponse>;

/** `GET /api/mods/find` result. (1 sample(s) from mod-find) */
export const LegacyModFind = dto(
  "LegacyModFind",
  z.strictObject({
    mod_id: z.string(),
  }),
  {
    description: "`GET /api/mods/find` result.",
    examples: [{
      "mod_id": "AxelModMenu"
    }],
  },
);
export type LegacyModFind = z.infer<typeof LegacyModFind>;

/** Envelope of `GET /api/mods/find`. (1 sample(s) from mod-find) */
export const LegacyModFindResponse = dto(
  "LegacyModFindResponse",
  z.strictObject({
    status: z.literal(true),
    data: LegacyModFind,
  }),
  {
    description: "Envelope of `GET /api/mods/find`.",
    examples: [{
      "status": true,
      "data": {
        "mod_id": "AxelModMenu"
      }
    }],
  },
);
export type LegacyModFindResponse = z.infer<typeof LegacyModFindResponse>;

/** `GET /api/mods/:mod_id/check` (node-semver `gt`); the three exact messages of research/01 §2.5. (3 sample(s) from check-outdated, check-current, check-noversion) */
export const LegacyCheckResponse = dto(
  "LegacyCheckResponse",
  z.strictObject({
    status: z.literal(true),
    newVersionAvailable: z.boolean(),
    message: z.enum(["New version available", "No new version available", "Latest version"]),
    version: z.string(),
    changelog: z.string(),
  }),
  {
    description: "`GET /api/mods/:mod_id/check` (node-semver `gt`); the three exact messages of research/01 §2.5.",
    examples: [{
      "status": true,
      "newVersionAvailable": true,
      "message": "New version available",
      "version": "1.3.8",
      "changelog": "Fixed noclip causing issues with riding ziplines and character physics override"
    }],
  },
);
export type LegacyCheckResponse = z.infer<typeof LegacyCheckResponse>;

/** Legacy error envelope (404 message is the Spanish literal "No se encontró el recurso."). (11 sample(s) from mods-limit-invalid, mod-find-missing-param, mod-404, check-invalid, check-build-uuid, check-404, user-404, comments-noparam, download-stats-invalid, auth-check-noauth, route-404) */
export const LegacyErrorResponse = dto(
  "LegacyErrorResponse",
  z.strictObject({
    status: z.literal(false),
    error: z.enum(["NOT_FOUND", "VALIDATION", "UNKNOWN", "GONE"]),
    message: z.string(),
  }),
  {
    description: "Legacy error envelope (404 message is the Spanish literal \"No se encontró el recurso.\").",
    examples: [{
      "status": false,
      "error": "UNKNOWN",
      "message": "\nInvalid `prisma.mod.findMany()` invocation:\n\n{\n  where: {\n    isApproved: undefined,\n    isNSFW: false,\n    type: \"Mod\"\n  },\n  include: {\n    images: {\n      select: {\n        isPrimary: true,\n   ..."
    }],
  },
);
export type LegacyErrorResponse = z.infer<typeof LegacyErrorResponse>;

/** Every generated legacy schema by name. */
export const LEGACY_SCHEMAS = {
  LegacyUserRef,
  LegacyCategoryRef,
  LegacyModListImage,
  LegacyModListVersion,
  LegacyFavoritesCount,
  LegacyListMeta,
  LegacyModListItem,
  LegacyModListResponse,
  LegacyModDetailImage,
  LegacyDownloadsCount,
  LegacyModDetailVersion,
  LegacyModDetail,
  LegacyModDetailResponse,
  LegacyFeaturedMod,
  LegacyFeaturedModsResponse,
  LegacyFeaturedBuild,
  LegacyFeaturedBuildsResponse,
  LegacyStats,
  LegacyStatsResponse,
  LegacyCategory,
  LegacyCategoriesResponse,
  LegacyUser,
  LegacyUserResponse,
  LegacyUserStats,
  LegacyUserStatsResponse,
  LegacyCommentReply,
  LegacyComment,
  LegacyCommentsResponse,
  LegacyDownloadStat,
  LegacyDownloadStatsResponse,
  LegacyModFind,
  LegacyModFindResponse,
  LegacyCheckResponse,
  LegacyErrorResponse,
} as const;
export type LegacySchemaName = keyof typeof LEGACY_SCHEMAS;

/** The golden fixtures (`fixtures/legacy/INDEX.tsv`) and the schema of each body. */
export const LEGACY_FIXTURES: ReadonlyArray<{
  name: string;
  route: string;
  status: number;
  contentType: string;
  schema: LegacySchemaName;
}> = [
  { name: "stats", route: "/api/stats", status: 200, contentType: "application/json", schema: "LegacyStatsResponse" },
  { name: "stats-builds", route: "/api/stats/builds", status: 200, contentType: "application/json", schema: "LegacyStatsResponse" },
  { name: "categories", route: "/api/categories", status: 200, contentType: "application/json", schema: "LegacyCategoriesResponse" },
  { name: "categories-build", route: "/api/categories?type=Build", status: 200, contentType: "application/json", schema: "LegacyCategoriesResponse" },
  { name: "mods-default", route: "/api/mods", status: 200, contentType: "application/json", schema: "LegacyModListResponse" },
  { name: "mods-redmanager-p1", route: "/api/mods?&approved=true&orderby=newest&page=1&nsfw=false", status: 200, contentType: "application/json", schema: "LegacyModListResponse" },
  { name: "mods-redmanager-unapproved", route: "/api/mods?&approved=false&orderby=newest&page=1&nsfw=false", status: 200, contentType: "application/json", schema: "LegacyModListResponse" },
  { name: "mods-redmanager-search", route: "/api/mods?&approved=true&orderby=newest&page=1&nsfw=false&search=kelvin", status: 200, contentType: "application/json", schema: "LegacyModListResponse" },
  { name: "mods-updateschecker-modids", route: "/api/mods?limit=5&modIds=AxelModMenu,SonsAxLib,UpdatesChecker,ItemSpawner,BuildShare", status: 200, contentType: "application/json", schema: "LegacyModListResponse" },
  { name: "mods-updateschecker-page", route: "/api/mods?&page=2", status: 200, contentType: "application/json", schema: "LegacyModListResponse" },
  { name: "mods-frontend-list", route: "/api/mods?nsfw=false&approved=true&orderby=newest&limit=16&type=Mod", status: 200, contentType: "application/json", schema: "LegacyModListResponse" },
  { name: "mods-type-build", route: "/api/mods?nsfw=false&approved=true&orderby=newest&limit=16&type=Build", status: 200, contentType: "application/json", schema: "LegacyModListResponse" },
  { name: "mods-user", route: "/api/mods?userSlug=imaxel&limit=100&approved=true", status: 200, contentType: "application/json", schema: "LegacyModListResponse" },
  { name: "mods-limit0", route: "/api/mods?limit=0", status: 200, contentType: "application/json", schema: "LegacyModListResponse" },
  { name: "mods-limit-invalid", route: "/api/mods?limit=abc", status: 500, contentType: "application/json", schema: "LegacyErrorResponse" },
  { name: "featured", route: "/api/mods/featured", status: 200, contentType: "application/json", schema: "LegacyFeaturedModsResponse" },
  { name: "builds-featured", route: "/api/builds/featured", status: 200, contentType: "application/json", schema: "LegacyFeaturedBuildsResponse" },
  { name: "mod-by-id", route: "/api/mods/AxelModMenu", status: 200, contentType: "application/json", schema: "LegacyModDetailResponse" },
  { name: "mod-by-id-build", route: "/api/mods/e215ede2e4d742398c72aaca62496c10", status: 200, contentType: "application/json", schema: "LegacyModDetailResponse" },
  { name: "mod-by-slug", route: "/api/mods/slug/imaxel/axel's-mod-menu", status: 200, contentType: "application/json", schema: "LegacyModDetailResponse" },
  { name: "mod-find", route: "/api/mods/find?userSlug=imaxel&mod_slug=axel's-mod-menu", status: 200, contentType: "application/json", schema: "LegacyModFindResponse" },
  { name: "mod-find-missing-param", route: "/api/mods/find?userSlug=imaxel", status: 422, contentType: "application/json", schema: "LegacyErrorResponse" },
  { name: "mod-404", route: "/api/mods/DoesNotExist123", status: 404, contentType: "application/json", schema: "LegacyErrorResponse" },
  { name: "check-outdated", route: "/api/mods/AxelModMenu/check?version=1.3.7", status: 200, contentType: "application/json", schema: "LegacyCheckResponse" },
  { name: "check-current", route: "/api/mods/AxelModMenu/check?version=1.3.8", status: 200, contentType: "application/json", schema: "LegacyCheckResponse" },
  { name: "check-noversion", route: "/api/mods/AxelModMenu/check", status: 200, contentType: "application/json", schema: "LegacyCheckResponse" },
  { name: "check-invalid", route: "/api/mods/AxelModMenu/check?version=notsemver", status: 500, contentType: "application/json", schema: "LegacyErrorResponse" },
  { name: "check-build-uuid", route: "/api/mods/e215ede2e4d742398c72aaca62496c10/check?version=1.0.0", status: 500, contentType: "application/json", schema: "LegacyErrorResponse" },
  { name: "check-404", route: "/api/mods/DoesNotExist123/check?version=1.0.0", status: 404, contentType: "application/json", schema: "LegacyErrorResponse" },
  { name: "user", route: "/api/users/imaxel", status: 200, contentType: "application/json", schema: "LegacyUserResponse" },
  { name: "user-stats", route: "/api/users/imaxel/stats", status: 200, contentType: "application/json", schema: "LegacyUserStatsResponse" },
  { name: "user-404", route: "/api/users/nobody-xyz-123", status: 404, contentType: "application/json", schema: "LegacyErrorResponse" },
  { name: "comments", route: "/api/comments?mod_id=20", status: 200, contentType: "application/json", schema: "LegacyCommentsResponse" },
  { name: "comments-noparam", route: "/api/comments", status: 500, contentType: "application/json", schema: "LegacyErrorResponse" },
  { name: "download-stats-week", route: "/api/mods/AxelModMenu/download-stats?period=week", status: 200, contentType: "application/json", schema: "LegacyDownloadStatsResponse" },
  { name: "download-stats-invalid", route: "/api/mods/AxelModMenu/download-stats?period=year", status: 422, contentType: "application/json", schema: "LegacyErrorResponse" },
  { name: "auth-check-noauth", route: "/api/auth/check", status: 500, contentType: "application/json", schema: "LegacyErrorResponse" },
  { name: "route-404", route: "/api/nonexistent-route", status: 404, contentType: "application/json", schema: "LegacyErrorResponse" },
];
