/**
 * Generates the static registries that PLAN §2.6 lists as "no se editan a mano":
 *
 * - apps/api/src/modules/_registry.gen.ts   default export of every `modules/<name>/index.ts`
 * - apps/worker/src/jobs/_registry.gen.ts   default export of every `jobs/<name>/index.ts`
 * - packages/db/src/schema/_index.gen.ts    `export *` barrel of `schema/{legacy,v2,ext}/*.ts`
 *
 * A registry is only (re)generated when its source directory exists, so the script is safe to run
 * before the owning WPs (WP-10, WP-20) create them. Output is deterministic (sorted, stable
 * identifiers) and needs no formatting.
 *
 *   node tooling/scripts/gen-registries.ts           # write
 *   node tooling/scripts/gen-registries.ts --check   # exit 1 if any registry is stale
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { color, fail, flagString, parseArgs } from './lib/cli.ts';
import { REPO_ROOT } from './lib/repo.ts';

export const HEADER =
  '// Code generated by `pnpm gen` (tooling/scripts/gen-registries.ts). DO NOT EDIT.\n' +
  '// Regenerate after adding, removing or renaming an entry; on merge conflicts, regenerate.\n';

/** A directory whose immediate subdirectories each default-export one entry from `index.ts`. */
export interface DefaultImportRegistry {
  kind: 'default-imports';
  /** Directory scanned, relative to the repository root. */
  dir: string;
  /** Output file, relative to `dir`. */
  output: string;
  /** Name of the exported array. */
  exportName: string;
  /** Suffix appended to each imported identifier (`auth` -> `authModule`). */
  identifierSuffix: string;
}

/** A barrel re-exporting every module of some subdirectories. */
export interface BarrelRegistry {
  kind: 'barrel';
  dir: string;
  output: string;
  /** Subdirectories of `dir` whose `*.ts` files are re-exported, in this order. */
  subdirs: readonly string[];
}

export type Registry = DefaultImportRegistry | BarrelRegistry;

export const REGISTRIES: readonly Registry[] = [
  {
    kind: 'default-imports',
    dir: 'apps/api/src/modules',
    output: '_registry.gen.ts',
    exportName: 'modules',
    identifierSuffix: 'Module',
  },
  {
    kind: 'default-imports',
    dir: 'apps/worker/src/jobs',
    output: '_registry.gen.ts',
    exportName: 'jobGroups',
    identifierSuffix: 'Jobs',
  },
  {
    kind: 'barrel',
    dir: 'packages/db/src/schema',
    output: '_index.gen.ts',
    subdirs: ['legacy', 'v2', 'ext'],
  },
];

/** `studio-mods` -> `studioMods`; guarantees a valid identifier. */
export function toIdentifier(name: string): string {
  const camel = name
    .replace(/[^A-Za-z0-9]+(.)?/g, (_, ch: string | undefined) => (ch ? ch.toUpperCase() : ''))
    .replace(/^[A-Z]/, (ch) => ch.toLowerCase());
  return /^[0-9]/.test(camel) ? `_${camel}` : camel;
}

const byName = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

function isEntryFile(name: string): boolean {
  return (
    name.endsWith('.ts') &&
    !name.endsWith('.d.ts') &&
    !name.endsWith('.test.ts') &&
    !name.endsWith('.gen.ts') &&
    !name.startsWith('_') &&
    name !== 'index.ts'
  );
}

/** Renders a registry's file content, or `null` when its directory does not exist. */
export function render(registry: Registry, root: string = REPO_ROOT): string | null {
  const dir = join(root, registry.dir);
  if (!existsSync(dir)) return null;
  if (registry.kind === 'default-imports') {
    const names = readdirSync(dir, { withFileTypes: true })
      .filter((e) => e.isDirectory() && !e.name.startsWith('_') && !e.name.startsWith('.'))
      .filter((e) => existsSync(join(dir, e.name, 'index.ts')))
      .map((e) => e.name)
      .sort(byName);
    const seen = new Map<string, string>();
    const lines = names.map((name) => {
      const id = `${toIdentifier(name)}${registry.identifierSuffix}`;
      const clash = seen.get(id);
      if (clash) throw new Error(`${registry.dir}: "${name}" and "${clash}" map to the same identifier ${id}`);
      seen.set(id, name);
      return { id, line: `import ${id} from './${name}/index.ts';` };
    });
    const body = lines.length
      ? `${lines.map((l) => l.line).join('\n')}\n\nexport const ${registry.exportName} = [\n${lines
          .map((l) => `  ${l.id},`)
          .join('\n')}\n] as const;\n`
      : `export const ${registry.exportName} = [] as const;\n`;
    return `${HEADER}\n${body}`;
  }
  const exports: string[] = [];
  for (const sub of registry.subdirs) {
    const subdir = join(dir, sub);
    if (!existsSync(subdir)) continue;
    const files = readdirSync(subdir, { withFileTypes: true })
      .filter((e) => e.isFile() && isEntryFile(e.name))
      .map((e) => e.name)
      .sort(byName);
    for (const file of files) exports.push(`export * from './${sub}/${file}';`);
  }
  return `${HEADER}\n${exports.length ? `${exports.join('\n')}\n` : 'export {};\n'}`;
}

export interface GenResult {
  path: string;
  status: 'written' | 'unchanged' | 'stale' | 'skipped';
}

export function generateAll(options: { check: boolean; root?: string }): GenResult[] {
  const root = options.root ?? REPO_ROOT;
  const results: GenResult[] = [];
  for (const registry of REGISTRIES) {
    const target = join(root, registry.dir, registry.output);
    const path = relative(root, target);
    const content = render(registry, root);
    if (content === null) {
      results.push({ path, status: 'skipped' });
      continue;
    }
    const existing = existsSync(target) ? readFileSync(target, 'utf8') : null;
    if (existing === content) {
      results.push({ path, status: 'unchanged' });
    } else if (options.check) {
      results.push({ path, status: 'stale' });
    } else {
      writeFileSync(target, content);
      results.push({ path, status: 'written' });
    }
  }
  return results;
}

function main(): void {
  const { flags } = parseArgs(process.argv.slice(2));
  const check = flags.has('check');
  const results = generateAll({ check, root: flagString(flags, 'root') });
  for (const r of results) {
    const label =
      r.status === 'stale' ? color.red(r.status) : r.status === 'written' ? color.green(r.status) : color.dim(r.status);
    process.stdout.write(`${label} ${r.path}\n`);
  }
  const stale = results.filter((r) => r.status === 'stale');
  if (stale.length > 0)
    fail(`${stale.length} generated registr${stale.length === 1 ? 'y is' : 'ies are'} stale: run \`pnpm gen\``);
}

if (import.meta.main) main();
