ALTER TABLE "Tag"
  DROP COLUMN IF EXISTS "group",
  DROP COLUMN IF EXISTS "i18n",
  DROP COLUMN IF EXISTS "isCurated",
  DROP COLUMN IF EXISTS "sortOrder";

ALTER TABLE "Category"
  DROP COLUMN IF EXISTS "icon",
  DROP COLUMN IF EXISTS "sortOrder",
  DROP COLUMN IF EXISTS "i18n",
  DROP COLUMN IF EXISTS "legacySlugs",
  DROP COLUMN IF EXISTS "retiredAt",
  DROP COLUMN IF EXISTS "hubIntro";
