-- Authentication (PLAN §6.4, §6.10). Opaque sessions in a __Host- cookie; only hashes are stored.
-- New tables use timestamptz(3); ids are uuid v7 generated by the application.

CREATE TABLE "Session" (
  "id" uuid NOT NULL,
  "userId" integer NOT NULL,
  "tokenHash" text NOT NULL,
  -- First 16 hex chars of sha256("User"."password"): a password change by any path (including
  -- the legacy API) invalidates the session.
  "pwdFingerprint" text NOT NULL,
  "createdAt" timestamptz(3) NOT NULL DEFAULT now(),
  "lastSeenAt" timestamptz(3) NOT NULL DEFAULT now(),
  "expiresAt" timestamptz(3) NOT NULL,
  "absoluteExpiresAt" timestamptz(3) NOT NULL,
  "revokedAt" timestamptz(3),
  "ipHash" text,
  "userAgent" text,
  "deviceLabel" text,
  CONSTRAINT "Session_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Session_tokenHash_key" UNIQUE ("tokenHash"),
  CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "Session_userId_active_idx" ON "Session"("userId") WHERE "revokedAt" IS NULL;

CREATE INDEX "Session_absoluteExpiresAt_idx" ON "Session"("absoluteExpiresAt");

CREATE TABLE "AuthToken" (
  "id" uuid NOT NULL,
  "userId" integer NOT NULL,
  "kind" text NOT NULL,
  "tokenHash" text NOT NULL,
  "payload" jsonb NOT NULL DEFAULT '{}',
  "expiresAt" timestamptz(3) NOT NULL,
  "usedAt" timestamptz(3),
  "createdAt" timestamptz(3) NOT NULL DEFAULT now(),
  CONSTRAINT "AuthToken_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "AuthToken_tokenHash_key" UNIQUE ("tokenHash"),
  CONSTRAINT "AuthToken_kind_check" CHECK ("kind" IN ('password_reset', 'email_verify', 'email_change')),
  CONSTRAINT "AuthToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "AuthToken_userId_kind_idx" ON "AuthToken"("userId", "kind");

CREATE INDEX "AuthToken_expiresAt_idx" ON "AuthToken"("expiresAt");

-- Security log, 90-day retention. No foreign key: it must outlive the rows it mentions.
CREATE TABLE "AuthEvent" (
  "id" bigint GENERATED ALWAYS AS IDENTITY,
  "userId" integer,
  "kind" text NOT NULL,
  "success" boolean NOT NULL,
  "ipHash" text,
  "userAgent" text,
  "createdAt" timestamptz(3) NOT NULL DEFAULT now(),
  CONSTRAINT "AuthEvent_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "AuthEvent_userId_createdAt_idx" ON "AuthEvent"("userId", "createdAt" DESC);

CREATE INDEX "AuthEvent_createdAt_brin" ON "AuthEvent" USING brin ("createdAt");
