-- Code generated by `pnpm --filter @sotf/db gen` (scripts/gen-seed-sql.ts). DO NOT EDIT.
-- sotf:allow-legacy-delete: removes only the "Category"/"Tag" rows that 0025 inserted (ids recorded in "MigrationRun") and that nothing references.
--
-- Rows that existed before the seed are left untouched (their v2 columns are dropped by the down
-- files of 0009). "retiredAt" disappears with its column.

DELETE FROM "LoaderRelease" AS l
WHERE l."id" IN (SELECT (jsonb_array_elements_text(r."notes" -> 'insertedIds'))::integer FROM "MigrationRun" AS r WHERE r."name" = '0025_seed_taxonomy:loader-releases')
  AND NOT EXISTS (SELECT 1 FROM "EcosystemStatus" AS e WHERE e."loaderReleaseId" = l."id");

DELETE FROM "Tag" AS t
WHERE t."id" IN (SELECT (jsonb_array_elements_text(r."notes" -> 'insertedIds'))::integer FROM "MigrationRun" AS r WHERE r."name" = '0025_seed_taxonomy:tags')
  AND NOT EXISTS (SELECT 1 FROM "_ModToTag" AS mt WHERE mt."B" = t."id");

DELETE FROM "Category" AS c
WHERE c."id" IN (SELECT (jsonb_array_elements_text(r."notes" -> 'insertedIds'))::integer FROM "MigrationRun" AS r WHERE r."name" = '0025_seed_taxonomy:categories')
  AND NOT EXISTS (SELECT 1 FROM "Mod" AS m WHERE m."categoryId" = c."id");

DELETE FROM "MigrationRun"
WHERE "name" IN ('0025_seed_taxonomy:categories', '0025_seed_taxonomy:tags', '0025_seed_taxonomy:loader-releases');
