DROP TABLE IF EXISTS "JamFollow";
DROP TABLE IF EXISTS "JamResult";
DROP TABLE IF EXISTS "JamVote";
DROP TABLE IF EXISTS "JamEntryAuthor";
DROP TABLE IF EXISTS "JamEntry";
DROP TABLE IF EXISTS "JamCategory";
DROP TABLE IF EXISTS "Jam";
