// Code generated by `pnpm gen` (tooling/scripts/gen-registries.ts). DO NOT EDIT.
// Regenerate after adding, removing or renaming an entry; on merge conflicts, regenerate.

import kelvinseekJobs from './kelvinseek/index.ts';
import platformJobs from './platform/index.ts';

export const jobGroups = [
  kelvinseekJobs,
  platformJobs,
] as const;
