// Code generated by `pnpm gen` (tooling/scripts/gen-registries.ts). DO NOT EDIT.
// Regenerate after adding, removing or renaming an entry; on merge conflicts, regenerate.

import accountsJobs from './accounts/index.ts';
import backfillJobs from './backfill/index.ts';
import buildsJobs from './builds/index.ts';
import cdnJobs from './cdn/index.ts';
import cleanupJobs from './cleanup/index.ts';
import compatJobs from './compat/index.ts';
import digestsJobs from './digests/index.ts';
import discordJobs from './discord/index.ts';
import discoveryJobs from './discovery/index.ts';
import downloadsJobs from './downloads/index.ts';
import emailJobs from './email/index.ts';
import gamificationJobs from './gamification/index.ts';
import indexnowJobs from './indexnow/index.ts';
import inspectionJobs from './inspection/index.ts';
import kelvinseekJobs from './kelvinseek/index.ts';
import legacyCountersJobs from './legacy-counters/index.ts';
import legacyMentionsJobs from './legacy-mentions/index.ts';
import mediaJobs from './media/index.ts';
import moderationJobs from './moderation/index.ts';
import notificationsJobs from './notifications/index.ts';
import ogJobs from './og/index.ts';
import platformJobs from './platform/index.ts';
import securityScanJobs from './security-scan/index.ts';
import statsJobs from './stats/index.ts';
import uploadsJobs from './uploads/index.ts';

export const jobGroups = [
  accountsJobs,
  backfillJobs,
  buildsJobs,
  cdnJobs,
  cleanupJobs,
  compatJobs,
  digestsJobs,
  discordJobs,
  discoveryJobs,
  downloadsJobs,
  emailJobs,
  gamificationJobs,
  indexnowJobs,
  inspectionJobs,
  kelvinseekJobs,
  legacyCountersJobs,
  legacyMentionsJobs,
  mediaJobs,
  moderationJobs,
  notificationsJobs,
  ogJobs,
  platformJobs,
  securityScanJobs,
  statsJobs,
  uploadsJobs,
] as const;
