/**
 * @sotf/api: Fastify 5 server (PLAN §2.1, §5): the v2 API under `/api/v2`, the byte-compatible legacy
 * surface under `/api/*`, the SSE hub, download redirects (302 to R2), KelvinSeek and internal
 * operations. Entry points: `src/server.ts` (HTTP), `src/migrate.ts` and `src/backfill.ts`.
 *
 * Domain modules live in `src/modules/<domain>/` (one `defineModule` default export each; the
 * registry is generated by `pnpm gen`) and the legacy layer in `src/legacy/**`.
 */
export { type BuildAppOptions, buildApp } from './app.ts';
export { type ApiEnv, parseApiEnv } from './env.ts';
export {
  type ApiModule,
  defineModule,
  type Handler,
  type HandlerInput,
  type HandlerOutput,
  implementEndpoint,
  type ModuleContext,
  type RedirectOutput,
  type TextOutput,
} from './lib/define-module.ts';
export { sendExactJson } from './lib/http.ts';
export type { EndpointRouteConfig, Platform, Readiness, SessionResolver } from './lib/types.ts';
export { renderError, sendError } from './plugins/errors.ts';
export { type BucketLimit, RateLimiter, SOFT_BUCKETS } from './plugins/rate-limit.ts';
export { channelsFor, formatFrame, SseHub } from './plugins/sse.ts';
