/**
 * WP-30 acceptance (`pnpm --filter @sotf/api test:int -- auth`), against PostgreSQL 16 (with
 * pg-boss) and a real Mailpit:
 *
 * - login with hashes generated by Bun (argon2id and `$2b$10$`) and the rehash to argon2id;
 * - one generic error with a timing within ±20 %; Turnstile after 3 failures;
 * - session revocations and the `pwdFingerprint` protection;
 * - Mailpit receives the verification email and the link verifies the account;
 * - password reset (v2 tokens and the legacy 24 h window), email change;
 * - the data export contains the expected JSON; the deletion anonymizes after the grace period;
 * - `/me` exposes the `can()` permissions of each role; `/me/home` cards; `PATCH /me/profile`.
 */
import { randomUUID } from 'node:crypto';
import { SESSION_COOKIE } from '@sotf/contracts/auth';
import { silentLogger, systemClock } from '@sotf/core';
import { executeDueDeletions, MemoryExportStorage, runExport } from '@sotf/core/accounts/index';
import { bunHash } from '@sotf/core/auth/fixtures/bun-hashes';
import type { BreachedPasswordChecker, TurnstileVerifier } from '@sotf/core/auth/index';
import { createSmtpTransport, deliverOutboxEmail, type EmailRenderer } from '@sotf/core/email/index';
import { authEvent, comment, emailOutbox, media, mod, passwordResetToken, session, upload, user } from '@sotf/db';
import { createFactories, type Factories } from '@sotf/db/testing';
import { type AccountEmailTemplate, renderAccountEmail } from '@sotf/emails/account/index';
import { and, desc, eq } from 'drizzle-orm';
import { strFromU8, unzipSync } from 'fflate';
import { GenericContainer, type StartedTestContainer, Wait } from 'testcontainers';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { buildTestApp, TEST_SITE_URL, type TestApp } from '../../testing.ts';
import { createAccountModules } from './modules.ts';

const BREACHED = 'password123456';
const hibp: BreachedPasswordChecker = { count: async (pw) => (pw === BREACHED ? 42 : 0) };
/** Turnstile that only accepts the literal token "human". */
const turnstile: TurnstileVerifier = { verify: async (token) => token === 'human' };
const storage = new MemoryExportStorage();

let t: TestApp;
let f: Factories;
let mailpit: StartedTestContainer;
let mailpitApi: string;
let smtpUrl: string;

const renderer: EmailRenderer = (template, locale, payload) =>
  renderAccountEmail(template as AccountEmailTemplate, locale, payload, TEST_SITE_URL);

let ipCounter = 0;
/** A fresh client IP per scenario keeps the failure counters and IP buckets independent. */
function newIp(): string {
  ipCounter += 1;
  return `198.51.100.${ipCounter}`;
}

function headers(ip: string, cookie?: string): Record<string, string> {
  return {
    ...t.sameOrigin(),
    'cf-connecting-ip': ip,
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0',
    ...(cookie ? { cookie: `${SESSION_COOKIE}=${cookie}` } : {}),
  };
}

function sessionCookieOf(res: { cookies: Array<{ name: string; value: string }> }): string {
  const found = res.cookies.find((c) => c.name === SESSION_COOKIE);
  if (!found?.value) throw new Error('no session cookie');
  return found.value;
}

async function post(url: string, body: unknown, ip: string, cookie?: string) {
  return t.app.inject({ method: 'POST', url, headers: headers(ip, cookie), payload: JSON.stringify(body ?? {}) });
}

async function del(url: string, ip: string, cookie?: string) {
  // The typed client always sends a JSON body on unsafe methods.
  return t.app.inject({ method: 'DELETE', url, headers: headers(ip, cookie), payload: '{}' });
}

async function get(url: string, ip: string, cookie?: string) {
  return t.app.inject({ method: 'GET', url, headers: headers(ip, cookie) });
}

async function login(identifier: string, password: string, ip = newIp(), extra: Record<string, unknown> = {}) {
  return post('/api/v2/auth/login', { identifier, password, remember: true, ...extra }, ip);
}

async function userWithPassword(hash: string, overrides: Parameters<Factories['user']>[0] = {}) {
  return f.user({ password: hash, emailVerifiedAt: new Date('2025-01-01T00:00:00Z'), ...overrides });
}

async function deliverQueued(): Promise<void> {
  const transport = createSmtpTransport({ url: smtpUrl });
  const rows = await t.db.db.select({ id: emailOutbox.id }).from(emailOutbox).where(eq(emailOutbox.status, 'queued'));
  for (const row of rows) {
    await deliverOutboxEmail(
      {
        db: t.db.db,
        transport,
        render: renderer,
        from: 'SOTF Mods <noreply@sotf-mods.com>',
        clock: systemClock,
        log: silentLogger(),
      },
      row.id,
    );
  }
}

interface MailpitSummary {
  ID: string;
  Subject: string;
  To: Array<{ Address: string }>;
}

async function mailpitMessages(to: string): Promise<MailpitSummary[]> {
  const res = await fetch(`${mailpitApi}/api/v1/search?query=${encodeURIComponent(`to:"${to}"`)}`);
  const body = (await res.json()) as { messages: MailpitSummary[] };
  return body.messages;
}

async function mailpitText(id: string): Promise<{ Text: string; HTML: string; Subject: string }> {
  const res = await fetch(`${mailpitApi}/api/v1/message/${id}`);
  return (await res.json()) as { Text: string; HTML: string; Subject: string };
}

async function lastOutbox(to: string, template: string) {
  const [row] = await t.db.db
    .select()
    .from(emailOutbox)
    .where(and(eq(emailOutbox.toEmail, to), eq(emailOutbox.template, template)))
    .orderBy(desc(emailOutbox.id))
    .limit(1);
  return row;
}

/** Empties the process LRUs (catalog snapshot, profiles) so each scenario reads fresh rows. */
function clearCaches(): void {
  t.app.platform.caches.invalidate('*');
}

function tokenFromUrl(url: string): string {
  const token = new URL(url).searchParams.get('token');
  if (!token) throw new Error(`no token in ${url}`);
  return token;
}

beforeAll(async () => {
  mailpit = await new GenericContainer('axllent/mailpit:v1.31.3')
    .withExposedPorts(1025, 8025)
    .withEnvironment({ MP_SMTP_AUTH_ACCEPT_ANY: '1', MP_SMTP_AUTH_ALLOW_INSECURE: '1' })
    .withWaitStrategy(Wait.forHttp('/readyz', 8025))
    .start();
  smtpUrl = `smtp://${mailpit.getHost()}:${mailpit.getMappedPort(1025)}`;
  mailpitApi = `http://${mailpit.getHost()}:${mailpit.getMappedPort(8025)}`;
  t = await buildTestApp({
    modules: createAccountModules({ hibp, turnstile, storage, failureFloorMs: 400 }),
    // The real session resolver of the auth module (not the header resolver of the test app).
    sessionResolver: undefined,
    rateLimits: {
      login: { max: 1000, window: '1 minute' },
      register: { max: 1000, window: '1 minute' },
      passwordForgot: { max: 1000, window: '1 minute' },
      emailResend: { max: 1000, window: '1 minute' },
    },
  });
  f = createFactories(t.db.db);
  // On a loaded host the event loop may still be catching up with the start-up work, and
  // @fastify/under-pressure answers 503 meanwhile: wait until the app serves requests normally.
  const deadline = Date.now() + 60_000;
  while ((await t.app.inject({ method: 'GET', url: '/api/v2/me' })).statusCode === 503) {
    if (Date.now() > deadline) throw new Error('the test app stayed under pressure for 60 s');
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
}, 240_000);

afterAll(async () => {
  await t?.close();
  await mailpit?.stop();
});

describe('login with the legacy (Bun) hashes', () => {
  it('argon2id from Bun: signs in, keeps the hash, returns the private user and a session cookie', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash, { slug: 'argon-user', email: 'argon@example.test' });
    const res = await login('argon@example.test', fixture.password);
    expect(res.statusCode).toBe(200);
    expect(res.json().user).toMatchObject({ id: account.id, handle: 'argon-user', emailVerified: true, role: 'user' });
    const cookie = res.cookies.find((c) => c.name === SESSION_COOKIE);
    expect(cookie).toMatchObject({ httpOnly: true, secure: true, sameSite: 'Lax', path: '/' });
    expect(res.cookies.find((c) => c.name === 'sotf_li')).toMatchObject({ value: '1', secure: true });
    expect(res.headers['cache-control']).toContain('no-store');
    const [row] = await t.db.db.select().from(user).where(eq(user.id, account.id));
    expect(row?.password).toBe(fixture.hash);
    expect(row?.lastLoginAt).toBeInstanceOf(Date);
    // The cookie authenticates /me.
    const me = await get('/api/v2/me', newIp(), sessionCookieOf(res));
    expect(me.statusCode).toBe(200);
    expect(me.json().user.id).toBe(account.id);
  });

  it('argon2id with Unicode: NFC and NFD input both work; login by handle is case-insensitive', async () => {
    const fixture = bunHash('argon2id-unicode-nfc');
    await userWithPassword(fixture.hash, { slug: 'Umlaut-User', email: 'umlaut@example.test' });
    expect((await login('umlaut-user', fixture.password)).statusCode).toBe(200);
    expect((await login('UMLAUT-USER', fixture.password.normalize('NFD'))).statusCode).toBe(200);
  });

  it.each(['bcrypt-ascii', 'bcrypt-long'] as const)(
    '%s from Bun: signs in and is rehashed to argon2id',
    async (name) => {
      const fixture = bunHash(name);
      expect(fixture.hash.startsWith('$2b$10$')).toBe(true);
      const account = await userWithPassword(fixture.hash);
      const res = await login(account.email, fixture.password);
      expect(res.statusCode).toBe(200);
      const [row] = await t.db.db.select().from(user).where(eq(user.id, account.id));
      expect(row?.password).toMatch(/^\$argon2id\$v=19\$m=65536,t=2,p=1\$/);
      expect(row?.passwordUpdatedAt).toBeInstanceOf(Date);
      const events = await t.db.db.select().from(authEvent).where(eq(authEvent.userId, account.id));
      expect(events.map((e) => e.kind)).toEqual(expect.arrayContaining(['rehash', 'login']));
      // The session created by that login is bound to the new hash and keeps working.
      expect((await get('/api/v2/me', newIp(), sessionCookieOf(res))).statusCode).toBe(200);
      // And the new hash verifies the same password.
      expect((await login(account.email, fixture.password)).statusCode).toBe(200);
    },
  );
});

describe('generic login error in constant time', () => {
  it('answers INVALID_CREDENTIALS for unknown accounts and wrong passwords alike', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const wrong = await login(account.email, 'not-the-password');
    const unknown = await login(`nobody-${randomUUID()}@example.test`, 'not-the-password');
    for (const res of [wrong, unknown]) {
      expect(res.statusCode).toBe(401);
      expect(res.headers['content-type']).toContain('application/problem+json');
    }
    const strip = (body: Record<string, unknown>) => ({ ...body, requestId: undefined, instance: undefined });
    expect(strip(wrong.json())).toEqual(strip(unknown.json()));
    expect(wrong.json().code).toBe('INVALID_CREDENTIALS');
  });

  it('takes the same time (±20 %) whether the account exists or not', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const timeOf = async (identifier: string) => {
      const ip = newIp();
      const started = performance.now();
      const res = await login(identifier, 'definitely-wrong', ip, { turnstileToken: 'human' });
      expect(res.statusCode).toBe(401);
      return performance.now() - started;
    };
    const median = (values: number[]) => [...values].sort((a, b) => a - b)[Math.floor(values.length / 2)] as number;
    const existing: number[] = [];
    const missing: number[] = [];
    for (let i = 0; i < 5; i += 1) {
      existing.push(await timeOf(account.email));
      missing.push(await timeOf(`ghost-${i}@example.test`));
    }
    const a = median(existing);
    const b = median(missing);
    expect(Math.abs(a - b) / Math.max(a, b)).toBeLessThanOrEqual(0.2);
  });

  it('requires Turnstile after 3 failures from the same client', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const ip = newIp();
    for (let i = 0; i < 3; i += 1) expect((await login(account.email, 'wrong-password', ip)).statusCode).toBe(401);
    const blocked = await login(account.email, fixture.password, ip);
    expect(blocked.statusCode).toBe(403);
    expect(blocked.json().code).toBe('TURNSTILE_REQUIRED');
    expect((await login(account.email, fixture.password, ip, { turnstileToken: 'bot' })).json().code).toBe(
      'TURNSTILE_REQUIRED',
    );
    expect((await login(account.email, fixture.password, ip, { turnstileToken: 'human' })).statusCode).toBe(200);
  });

  it('refuses banned accounts with SUSPENDED and never resolves their sessions', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const res = await login(account.email, fixture.password);
    await t.db.db.update(user).set({ bannedAt: new Date() }).where(eq(user.id, account.id));
    expect((await get('/api/v2/me', newIp(), sessionCookieOf(res))).statusCode).toBe(401);
    const again = await login(account.email, fixture.password);
    expect(again.statusCode).toBe(403);
    expect(again.json().code).toBe('SUSPENDED');
  });
});

describe('sessions and revocation', () => {
  it('lists sessions, revokes one, the others and logs out', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const a = sessionCookieOf(await login(account.email, fixture.password));
    const b = sessionCookieOf(await login(account.email, fixture.password));
    const c = sessionCookieOf(await login(account.email, fixture.password));

    const list = await get('/api/v2/me/sessions', newIp(), a);
    expect(list.statusCode).toBe(200);
    const items = list.json().items as Array<{
      id: string;
      current: boolean;
      deviceLabel: string;
      country: string | null;
    }>;
    expect(items).toHaveLength(3);
    expect(items.filter((s) => s.current)).toHaveLength(1);
    expect(items[0]?.deviceLabel).toBe('Firefox on Windows');
    // Sessions created without an edge country header carry none.
    expect(items.every((s) => s.country === null)).toBe(true);
    const current = items.find((s) => s.current)?.id as string;
    const others = items.filter((s) => !s.current).map((s) => s.id);

    // Revoke one other session.
    const revokedOne = await del(`/api/v2/me/sessions/${others[0]}`, newIp(), a);
    expect(revokedOne.statusCode).toBe(204);
    const stillValid = await Promise.all(
      [b, c].map(async (cookie) => (await get('/api/v2/me', newIp(), cookie)).statusCode),
    );
    expect(stillValid.sort()).toEqual([200, 401]);
    // Someone else's or unknown session → 404.
    const missing = await del(`/api/v2/me/sessions/${randomUUID()}`, newIp(), a);
    expect(missing.statusCode).toBe(404);

    // Revoke every other session.
    const all = await del('/api/v2/me/sessions', newIp(), a);
    expect(all.statusCode).toBe(204);
    expect((await get('/api/v2/me', newIp(), b)).statusCode).toBe(401);
    expect((await get('/api/v2/me', newIp(), c)).statusCode).toBe(401);
    expect((await get('/api/v2/me', newIp(), a)).statusCode).toBe(200);

    // Logout revokes the current one and clears both cookies.
    const out = await post('/api/v2/auth/logout', {}, newIp(), a);
    expect(out.statusCode).toBe(204);
    const cleared = out.cookies.find((cookie) => cookie.name === SESSION_COOKIE);
    expect(cleared?.value).toBe('');
    expect((await get('/api/v2/me', newIp(), a)).statusCode).toBe(401);
    const [row] = await t.db.db.select().from(session).where(eq(session.id, current));
    expect(row?.revokedAt).toBeInstanceOf(Date);
  });

  it('stores the edge country of the request that created the session and lists it to the owner', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const withCountry = await t.app.inject({
      method: 'POST',
      url: '/api/v2/auth/login',
      headers: { ...headers(newIp()), 'cf-ipcountry': 'es' },
      payload: JSON.stringify({ identifier: account.email, password: fixture.password, remember: true }),
    });
    expect(withCountry.statusCode).toBe(200);
    const unknown = await t.app.inject({
      method: 'POST',
      url: '/api/v2/auth/login',
      headers: { ...headers(newIp()), 'cf-ipcountry': 'XX' },
      payload: JSON.stringify({ identifier: account.email, password: fixture.password, remember: true }),
    });
    expect(unknown.statusCode).toBe(200);
    const list = await get('/api/v2/me/sessions', newIp(), sessionCookieOf(withCountry));
    const items = list.json().items as Array<{ current: boolean; country: string | null }>;
    expect(items.find((s) => s.current)?.country).toBe('ES');
    expect(items.find((s) => !s.current)?.country).toBeNull();
  });

  it('expired sessions do not resolve; short sessions last 24 h without renewal', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const res = await post(
      '/api/v2/auth/login',
      { identifier: account.email, password: fixture.password, remember: false },
      newIp(),
    );
    const cookie = res.cookies.find((c) => c.name === SESSION_COOKIE);
    expect(cookie?.maxAge).toBeUndefined();
    const [row] = await t.db.db.select().from(session).where(eq(session.userId, account.id));
    expect(row && row.absoluteExpiresAt.getTime() - row.createdAt.getTime()).toBe(24 * 3600 * 1000);
    await t.db.db
      .update(session)
      .set({ expiresAt: new Date(Date.now() - 1000) })
      .where(eq(session.userId, account.id));
    expect((await get('/api/v2/me', newIp(), cookie?.value)).statusCode).toBe(401);
    expect((await get('/api/v2/me', newIp(), 'not-a-real-token')).statusCode).toBe(401);
  });

  it('slides a remembered session when less than 15 days are left', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const cookie = sessionCookieOf(await login(account.email, fixture.password));
    const soon = new Date(Date.now() + 2 * 24 * 3600 * 1000);
    await t.db.db.update(session).set({ expiresAt: soon }).where(eq(session.userId, account.id));
    expect((await get('/api/v2/me/summary', newIp(), cookie)).statusCode).toBe(200);
    const [row] = await t.db.db.select().from(session).where(eq(session.userId, account.id));
    expect(row && row.expiresAt.getTime() - Date.now()).toBeGreaterThan(29 * 24 * 3600 * 1000);
  });

  it('pwdFingerprint: a password changed elsewhere (legacy API) invalidates existing sessions', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const cookie = sessionCookieOf(await login(account.email, fixture.password));
    expect((await get('/api/v2/me', newIp(), cookie)).statusCode).toBe(200);
    // The legacy API writes a new Bun hash directly.
    await t.db.db
      .update(user)
      .set({ password: bunHash('argon2id-unicode-nfc').hash })
      .where(eq(user.id, account.id));
    expect((await get('/api/v2/me', newIp(), cookie)).statusCode).toBe(401);
  });

  it('changing the password revokes the other sessions and keeps the current one', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const current = sessionCookieOf(await login(account.email, fixture.password));
    const other = sessionCookieOf(await login(account.email, fixture.password));
    const wrong = await post(
      '/api/v2/me/password',
      { current: 'nope', next: 'a-new-long-passphrase' },
      newIp(),
      current,
    );
    expect(wrong.statusCode).toBe(401);
    expect(wrong.json().code).toBe('INVALID_CREDENTIALS');
    const breached = await post('/api/v2/me/password', { current: fixture.password, next: BREACHED }, newIp(), current);
    expect(breached.statusCode).toBe(422);
    expect(breached.json().errors[0].code).toBe('password_breached');
    const ok = await post(
      '/api/v2/me/password',
      { current: fixture.password, next: 'a-new-long-passphrase', revokeOthers: true },
      newIp(),
      current,
    );
    expect(ok.statusCode).toBe(204);
    expect((await get('/api/v2/me', newIp(), current)).statusCode).toBe(200);
    expect((await get('/api/v2/me', newIp(), other)).statusCode).toBe(401);
    expect((await login(account.email, 'a-new-long-passphrase')).statusCode).toBe(200);
    expect(await lastOutbox(account.email, 'auth.password_changed')).toBeTruthy();
  });
});

describe('registration and email verification (Mailpit)', () => {
  it('registers, emails the verification link through Mailpit and verifies the account', async () => {
    const email = `new-${randomUUID().slice(0, 8)}@example.test`;
    const res = await post(
      '/api/v2/auth/register',
      {
        email,
        handle: 'fresh-survivor',
        password: 'kelvin-carries-logs-2026',
        displayName: 'Fresh Survivor',
        locale: 'es',
        acceptTerms: true,
        turnstileToken: 'human',
      },
      newIp(),
    );
    expect(res.statusCode).toBe(201);
    const body = res.json();
    expect(body.user).toMatchObject({
      handle: 'fresh-survivor',
      displayName: 'Fresh Survivor',
      emailVerified: false,
      locale: 'es',
      trustLevel: 0,
    });
    const cookie = sessionCookieOf(res);

    // Outbox row + email.send job in the same transaction.
    const outbox = await lastOutbox(email, 'auth.verify_email');
    expect(outbox).toMatchObject({ status: 'queued', locale: 'es' });
    const jobs = await t.db.pool.query(
      `SELECT count(*)::int AS n FROM pgboss.job WHERE name = 'email.send' AND data->>'outboxId' = $1`,
      [String(outbox?.id)],
    );
    expect(jobs.rows[0].n).toBe(1);
    const events = await t.db.pool.query(
      `SELECT count(*)::int AS n FROM pgboss.job WHERE name = 'domain.event' AND data->>'type' = 'user.registered'
       AND (data->'payload'->>'userId')::int = $1`,
      [body.user.id],
    );
    expect(events.rows[0].n).toBe(1);

    // Unverified accounts cannot write.
    const me = await get('/api/v2/me', newIp(), cookie);
    expect(me.json().flags.mustVerifyEmail).toBe(true);
    expect(me.json().permissions).toEqual([]);

    await deliverQueued();
    const [sent] = await t.db.db
      .select()
      .from(emailOutbox)
      .where(eq(emailOutbox.id, outbox?.id as number));
    expect(sent?.status).toBe('sent');
    const messages = await mailpitMessages(email);
    expect(messages).toHaveLength(1);
    expect(messages[0]?.Subject).toBe('Confirma tu correo en SOTF Mods');
    const message = await mailpitText(messages[0]?.ID as string);
    const link = /https:\/\/sotf-mods\.test\/es\/verify-email\?token=[A-Za-z0-9_-]{43}/.exec(message.Text)?.[0];
    expect(link).toBeTruthy();
    expect(message.HTML).toContain('lang="es"');

    const verified = await post('/api/v2/auth/email/verify', { token: tokenFromUrl(link as string) }, newIp());
    expect(verified.statusCode).toBe(204);
    const after = await get('/api/v2/me', newIp(), cookie);
    expect(after.json().user.emailVerified).toBe(true);
    expect(after.json().permissions).toContain('comment.write');
    // Single use.
    const reuse = await post('/api/v2/auth/email/verify', { token: tokenFromUrl(link as string) }, newIp());
    expect(reuse.statusCode).toBe(404);
    // Resend on a verified account → 409.
    expect((await post('/api/v2/auth/email/resend', {}, newIp(), cookie)).statusCode).toBe(409);
  });

  it('resend issues a new link and retires the previous one', async () => {
    const email = `resend-${randomUUID().slice(0, 8)}@example.test`;
    const res = await post(
      '/api/v2/auth/register',
      {
        email,
        handle: `resend-${randomUUID().slice(0, 6)}`,
        password: 'kelvin-carries-logs-2026',
        locale: 'en',
        acceptTerms: true,
        turnstileToken: 'human',
      },
      newIp(),
    );
    const first = tokenFromUrl(String((await lastOutbox(email, 'auth.verify_email'))?.payload.url));
    expect((await post('/api/v2/auth/email/resend', {}, newIp(), sessionCookieOf(res))).statusCode).toBe(202);
    const second = tokenFromUrl(String((await lastOutbox(email, 'auth.verify_email'))?.payload.url));
    expect(second).not.toBe(first);
    expect((await post('/api/v2/auth/email/verify', { token: first }, newIp())).statusCode).toBe(404);
    expect((await post('/api/v2/auth/email/verify', { token: second }, newIp())).statusCode).toBe(204);
  });

  it('rejects bots, reserved handles, disposable domains, breached passwords and duplicates', async () => {
    const valid = {
      email: 'valid@example.test',
      handle: 'valid-handle',
      password: 'kelvin-carries-logs-2026',
      locale: 'en',
      acceptTerms: true,
      turnstileToken: 'human',
    };
    const bot = await post('/api/v2/auth/register', { ...valid, turnstileToken: 'robot' }, newIp());
    expect(bot.json().code).toBe('TURNSTILE_REQUIRED');
    const reserved = await post('/api/v2/auth/register', { ...valid, handle: 'basecamp' }, newIp());
    expect(reserved.statusCode).toBe(422);
    const disposable = await post('/api/v2/auth/register', { ...valid, email: 'x@mailinator.com' }, newIp());
    expect(disposable.statusCode).toBe(422);
    expect(disposable.json().errors[0].code).toBe('email_disposable');
    const breached = await post('/api/v2/auth/register', { ...valid, password: BREACHED }, newIp());
    expect(breached.statusCode).toBe(422);
    expect(breached.json().errors[0].code).toBe('password_breached');
    const short = await post('/api/v2/auth/register', { ...valid, password: 'short' }, newIp());
    expect(short.statusCode).toBe(422);
    await f.user({ email: 'Taken@Example.test', slug: 'taken-handle' });
    const dupEmail = await post('/api/v2/auth/register', { ...valid, email: 'taken@example.test' }, newIp());
    expect(dupEmail.statusCode).toBe(409);
    expect(dupEmail.json().errors[0].code).toBe('email_taken');
    const dupHandle = await post('/api/v2/auth/register', { ...valid, handle: 'Taken-Handle' }, newIp());
    expect(dupHandle.statusCode).toBe(409);
    expect(dupHandle.json().errors[0].code).toBe('handle_taken');
  });
});

describe('password reset', () => {
  it('always answers 202 and emails a single-use 1 h link to existing accounts', async () => {
    const fixture = bunHash('bcrypt-ascii');
    const account = await userWithPassword(fixture.hash);
    const old = sessionCookieOf(await login(account.email, fixture.password));
    const unknown = await post(
      '/api/v2/auth/password/forgot',
      { email: 'ghost@example.test', turnstileToken: 'human' },
      newIp(),
    );
    expect(unknown.statusCode).toBe(202);
    expect(await lastOutbox('ghost@example.test', 'auth.password_reset')).toBeUndefined();
    const known = await post(
      '/api/v2/auth/password/forgot',
      { email: account.email.toUpperCase(), turnstileToken: 'human' },
      newIp(),
    );
    expect(known.statusCode).toBe(202);
    const outbox = await lastOutbox(account.email, 'auth.password_reset');
    const token = tokenFromUrl(String(outbox?.payload.url));

    const reset = await post('/api/v2/auth/password/reset', { token, password: 'fresh-passphrase-2026' }, newIp());
    expect(reset.statusCode).toBe(204);
    expect((await get('/api/v2/me', newIp(), old)).statusCode).toBe(401);
    expect((await login(account.email, 'fresh-passphrase-2026')).statusCode).toBe(200);
    expect(
      (await post('/api/v2/auth/password/reset', { token, password: 'another-passphrase-1' }, newIp())).statusCode,
    ).toBe(404);

    // Expired links answer 410.
    await post('/api/v2/auth/password/forgot', { email: account.email, turnstileToken: 'human' }, newIp());
    const expiring = tokenFromUrl(String((await lastOutbox(account.email, 'auth.password_reset'))?.payload.url));
    await t.db.pool.query(
      `UPDATE "AuthToken" SET "expiresAt" = now() - interval '1 minute' WHERE "userId" = $1 AND "usedAt" IS NULL`,
      [account.id],
    );
    expect(
      (await post('/api/v2/auth/password/reset', { token: expiring, password: 'another-passphrase-1' }, newIp()))
        .statusCode,
    ).toBe(410);
  });

  it('accepts a legacy PasswordResetToken once during its 24 h window and deletes it', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const legacyToken = randomUUID();
    await t.db.db.insert(passwordResetToken).values({
      token: legacyToken,
      userId: account.id,
      expiresAt: new Date(Date.now() + 3600 * 1000),
    });
    const res = await post(
      '/api/v2/auth/password/reset',
      { token: legacyToken, password: 'legacy-window-pass' },
      newIp(),
    );
    expect(res.statusCode).toBe(204);
    expect(await t.db.db.select().from(passwordResetToken).where(eq(passwordResetToken.token, legacyToken))).toEqual(
      [],
    );
    expect((await login(account.email, 'legacy-window-pass')).statusCode).toBe(200);

    const stale = randomUUID();
    await t.db.db.insert(passwordResetToken).values({
      token: stale,
      userId: account.id,
      expiresAt: new Date(Date.now() + 3600 * 1000),
      createdAt: new Date(Date.now() - 25 * 3600 * 1000),
    });
    expect(
      (await post('/api/v2/auth/password/reset', { token: stale, password: 'legacy-window-pass2' }, newIp()))
        .statusCode,
    ).toBe(410);
  });
});

describe('email change', () => {
  it('confirms the new address and warns the old one', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash);
    const cookie = sessionCookieOf(await login(account.email, fixture.password));
    const newEmail = `moved-${randomUUID().slice(0, 8)}@example.test`;
    expect((await post('/api/v2/me/email', { newEmail, password: 'wrong' }, newIp(), cookie)).statusCode).toBe(401);
    expect((await post('/api/v2/me/email', { newEmail, password: fixture.password }, newIp(), cookie)).statusCode).toBe(
      202,
    );
    const notice = await lastOutbox(account.email, 'auth.email_change_notice');
    expect(notice?.payload.newEmailMasked).toMatch(/^m\*\*\*@example\.test$/);
    const confirm = await lastOutbox(newEmail, 'auth.email_change_confirm');
    await deliverQueued();
    expect(await mailpitMessages(newEmail)).toHaveLength(1);
    expect(await mailpitMessages(account.email)).not.toHaveLength(0);
    const res = await post('/api/v2/auth/email/verify', { token: tokenFromUrl(String(confirm?.payload.url)) }, newIp());
    expect(res.statusCode).toBe(204);
    const me = await get('/api/v2/me', newIp(), cookie);
    expect(me.json().user.email).toBe(newEmail);
  });
});

describe('data export', () => {
  it('queues, builds the ZIP with the expected JSON and serves a presigned link', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash, { slug: 'exporter', email: 'exporter@example.test' });
    const cookie = sessionCookieOf(await login(account.email, fixture.password));
    const { mod: own } = await f.modWithVersion({ userId: account.id });
    const other = await f.mod();
    await f.comment({ modId: other.id, userId: account.id, message: 'Works on the latest patch' });
    await f.favorite({ userId: account.id, modId: other.id });

    const res = await post('/api/v2/me/export', {}, newIp(), cookie);
    expect(res.statusCode).toBe(202);
    const created = res.json();
    expect(created).toMatchObject({ status: 'queued', downloadUrl: null });
    expect((await post('/api/v2/me/export', {}, newIp(), cookie)).statusCode).toBe(429);

    const outcome = await runExport(
      {
        db: t.db.db,
        jobs: t.app.platform.jobs,
        clock: systemClock,
        log: silentLogger(),
        storage,
        siteUrl: TEST_SITE_URL,
      },
      created.id,
    );
    expect(outcome).toBe('ready');
    const object = storage.objects.get(`exports/${account.id}/${created.id}.zip`);
    expect(object?.contentType).toBe('application/zip');
    const files = unzipSync(object?.body as Uint8Array);
    const json = (name: string) => JSON.parse(strFromU8(files[name] as Uint8Array));
    expect(Object.keys(files)).toEqual(
      expect.arrayContaining([
        'README.txt',
        'export.json',
        'account.json',
        'mods.json',
        'comments.json',
        'sessions.json',
      ]),
    );
    const accountJson = json('account.json');
    expect(accountJson).toMatchObject({ id: account.id, email: 'exporter@example.test', slug: 'exporter' });
    expect(accountJson).not.toHaveProperty('password');
    expect(json('export.json')).toMatchObject({ format: 1, userId: account.id });
    expect(json('mods.json').map((m: { id: number }) => m.id)).toEqual([own.id]);
    expect(json('mod-versions.json')).toHaveLength(1);
    expect(json('comments.json').map((c: { message: string }) => c.message)).toEqual(['Works on the latest patch']);
    expect(json('favorites.json').map((x: { modId: number }) => x.modId)).toEqual([other.id]);
    const sessions = json('sessions.json');
    expect(sessions.length).toBeGreaterThan(0);
    for (const s of sessions) {
      expect(s).not.toHaveProperty('tokenHash');
      expect(s).not.toHaveProperty('pwdFingerprint');
    }
    expect(json('security-log.json').some((e: { kind: string }) => e.kind === 'login')).toBe(true);

    const status = await get(`/api/v2/me/exports/${created.id}`, newIp(), cookie);
    expect(status.json()).toMatchObject({ status: 'ready' });
    expect(status.json().downloadUrl).toContain(`exports/${account.id}/${created.id}.zip`);
    const email = await lastOutbox(account.email, 'account.export_ready');
    expect(email?.payload.url).toContain(`exports/${account.id}/${created.id}.zip`);
    // Someone else's export → 404.
    const stranger = sessionCookieOf(await login((await userWithPassword(fixture.hash)).email, fixture.password));
    expect((await get(`/api/v2/me/exports/${created.id}`, newIp(), stranger)).statusCode).toBe(404);
  });
});

describe('account deletion', () => {
  it('schedules with a password, can be cancelled, and anonymizes after the 14-day grace period', async () => {
    const fixture = bunHash('argon2id-ascii');
    const account = await userWithPassword(fixture.hash, {
      slug: 'leaving-survivor',
      email: 'leaving@example.test',
      displayName: 'Leaving',
    });
    const cookie = sessionCookieOf(await login(account.email, fixture.password));
    const { mod: published } = await f.modWithVersion({ userId: account.id });
    const target = await f.mod();
    const written = await f.comment({ modId: target.id, userId: account.id, message: 'Great mod' });
    await f.favorite({ userId: account.id, modId: target.id });

    const wrong = await post('/api/v2/me/delete', { password: 'nope' }, newIp(), cookie);
    expect(wrong.json().code).toBe('INVALID_CREDENTIALS');
    const scheduled = await post('/api/v2/me/delete', { password: fixture.password }, newIp(), cookie);
    expect(scheduled.statusCode).toBe(202);
    const due = new Date(scheduled.json().executeAfter);
    expect(Math.round((due.getTime() - Date.now()) / (24 * 3600 * 1000))).toBe(14);
    expect(scheduled.json().mode).toBe('archive_mods');
    expect((await post('/api/v2/me/delete', { password: fixture.password }, newIp(), cookie)).statusCode).toBe(409);
    expect((await get('/api/v2/me', newIp(), cookie)).json().user.deletionScheduledAt).toBe(
      scheduled.json().executeAfter,
    );

    // Cancel and schedule again.
    expect((await post('/api/v2/me/delete/cancel', {}, newIp(), cookie)).statusCode).toBe(204);
    expect((await get('/api/v2/me', newIp(), cookie)).json().user.deletionScheduledAt).toBeNull();
    expect((await post('/api/v2/me/delete/cancel', {}, newIp(), cookie)).statusCode).toBe(404);
    expect((await post('/api/v2/me/delete', { password: fixture.password }, newIp(), cookie)).statusCode).toBe(202);

    const deps = { db: t.db.db, jobs: t.app.platform.jobs, log: silentLogger(), storage };
    // Not yet due: nothing happens.
    expect(await executeDueDeletions({ ...deps, clock: systemClock })).toEqual([]);
    // After the grace period the sweep anonymizes the account.
    const later = { now: () => new Date(Date.now() + 15 * 24 * 3600 * 1000) };
    expect(await executeDueDeletions({ ...deps, clock: later })).toEqual([account.id]);

    const [row] = await t.db.db.select().from(user).where(eq(user.id, account.id));
    expect(row).toMatchObject({
      email: `deleted-${account.id}@deleted.invalid`,
      slug: `deleted-${account.id}`,
      name: 'Deleted survivor',
      displayName: null,
      password: '!deleted',
      emailVerifiedAt: null,
    });
    expect(row?.deletedAt).toBeInstanceOf(Date);
    // Comments stay, attributed to the anonymized account.
    const [kept] = await t.db.db.select().from(comment).where(eq(comment.id, written.id));
    expect(kept).toMatchObject({ userId: account.id, message: 'Great mod' });
    // Mods archived, favorites and sessions gone.
    const [archived] = await t.db.db.select().from(mod).where(eq(mod.id, published.id));
    expect(archived?.status).toBe('archived');
    const favorites = await t.db.pool.query(`SELECT count(*)::int AS n FROM "ModFavorite" WHERE "userId" = $1`, [
      account.id,
    ]);
    expect(favorites.rows[0].n).toBe(0);
    expect(await t.db.db.select().from(session).where(eq(session.userId, account.id))).toEqual([]);
    expect((await get('/api/v2/me', newIp(), cookie)).statusCode).toBe(401);
    expect((await login('leaving@example.test', fixture.password)).statusCode).toBe(401);
    // Goodbye email to the old address; nothing else keeps it.
    expect(await lastOutbox('leaving@example.test', 'account.deletion_completed')).toBeTruthy();
    // Idempotent.
    expect(await executeDueDeletions({ ...deps, clock: later })).toEqual([]);
  });
});

describe('/me', () => {
  it('returns permissions from can() for each role, summary, home, settings and privacy', async () => {
    const fixture = bunHash('argon2id-ascii');
    const moderator = await userWithPassword(fixture.hash, { role: 'moderator' });
    const admin = await userWithPassword(fixture.hash, { role: 'admin' });
    const creator = await userWithPassword(fixture.hash, { verifiedCreator: true });
    const permissions = async (email: string) =>
      (await get('/api/v2/me', newIp(), sessionCookieOf(await login(email, fixture.password)))).json()
        .permissions as string[];
    expect(await permissions(moderator.email)).toEqual(
      expect.arrayContaining(['moderation.queue', 'moderation.sanction']),
    );
    expect(await permissions(moderator.email)).not.toContain('admin.roles');
    expect(await permissions(admin.email)).toContain('admin.roles');
    expect(await permissions(creator.email)).toContain('mod.publish_without_review');

    const cookie = sessionCookieOf(await login(creator.email, fixture.password));
    const summary = await get('/api/v2/me/summary', newIp(), cookie);
    expect(summary.json()).toMatchObject({ id: creator.id, emailVerified: true, unreadNotifications: 0 });
    expect(summary.headers['cache-control']).toContain('private');

    const home = await get('/api/v2/me/home', newIp(), cookie);
    expect(home.json()).toMatchObject({ updatesCount: 0, updates: [], recentKits: [] });
    expect(home.json().onboarding.steps).toHaveLength(5);

    const settings = await t.app.inject({
      method: 'PATCH',
      url: '/api/v2/me/settings',
      headers: headers(newIp(), cookie),
      payload: JSON.stringify({ theme: 'dark', nsfwOptIn: true, confirmAdult: true, locale: 'de' }),
    });
    expect(settings.statusCode).toBe(200);
    expect(settings.json()).toMatchObject({ theme: 'dark', nsfwOptIn: true, locale: 'de', downloadHistory: true });
    expect(settings.json().nsfwConfirmedAt).not.toBeNull();
    const privacy = await t.app.inject({
      method: 'PATCH',
      url: '/api/v2/me/privacy',
      headers: headers(newIp(), cookie),
      payload: JSON.stringify({ hideActivity: true }),
    });
    expect(privacy.json()).toEqual({
      hideActivity: true,
      hideRank: false,
      hideFromLeaderboards: false,
      hideKits: false,
    });
    const me = (await get('/api/v2/me', newIp(), cookie)).json();
    expect(me.settings.theme).toBe('dark');
    expect(me.user.locale).toBe('de');
    expect(me.privacy.hideActivity).toBe(true);
  });

  it('counts followed mods with an update since the last download', async () => {
    const fixture = bunHash('argon2id-ascii');
    const reader = await userWithPassword(fixture.hash);
    const { mod: followed, version: v1 } = await f.modWithVersion(
      {},
      { version: '1.0.0', createdAt: new Date('2026-01-01T00:00:00Z') },
    );
    await f.favorite({ userId: reader.id, modId: followed.id });
    await f.download({ modVersionId: v1.id, userId: reader.id, createdAt: new Date('2026-02-01T00:00:00Z') });
    await t.db.pool.query(`UPDATE "ModVersion" SET "isLatest" = false WHERE "id" = $1`, [v1.id]);
    await f.modVersion({
      modId: followed.id,
      version: '1.1.0',
      isLatest: true,
      createdAt: new Date('2026-03-01T00:00:00Z'),
    });
    const cookie = sessionCookieOf(await login(reader.email, fixture.password));
    clearCaches();
    const home = (await get('/api/v2/me/home', newIp(), cookie)).json();
    expect(home.updatesCount).toBe(1);
    expect(home.updates).toHaveLength(1);
    expect(home.updates[0]).toMatchObject({ fromVersion: '1.0.0', toVersion: '1.1.0' });
    expect(home.updates[0].mod).toMatchObject({ id: followed.id, latestVersion: '1.1.0' });
    expect(home.onboarding.steps.find((s: { key: string }) => s.key === 'first_download').done).toBe(true);
    expect(home.onboarding.steps.find((s: { key: string }) => s.key === 'follow_mod').done).toBe(true);
  });

  it('shows NSFW update cards only to users who opted in', async () => {
    const fixture = bunHash('argon2id-ascii');
    const reader = await userWithPassword(fixture.hash);
    const { mod: nsfw, version: v1 } = await f.modWithVersion(
      { isNSFW: true },
      { version: '2.0.0', createdAt: new Date('2026-01-01T00:00:00Z') },
    );
    await f.favorite({ userId: reader.id, modId: nsfw.id });
    await f.download({ modVersionId: v1.id, userId: reader.id, createdAt: new Date('2026-02-01T00:00:00Z') });
    await t.db.pool.query(`UPDATE "ModVersion" SET "isLatest" = false WHERE "id" = $1`, [v1.id]);
    await f.modVersion({
      modId: nsfw.id,
      version: '2.1.0',
      isLatest: true,
      createdAt: new Date('2026-03-01T00:00:00Z'),
    });
    const cookie = sessionCookieOf(await login(reader.email, fixture.password));
    clearCaches();
    const hidden = (await get('/api/v2/me/home', newIp(), cookie)).json();
    expect(hidden.updatesCount).toBe(1);
    expect(hidden.updates).toEqual([]);
    await t.app.inject({
      method: 'PATCH',
      url: '/api/v2/me/settings',
      headers: headers(newIp(), cookie),
      payload: JSON.stringify({ nsfwOptIn: true, confirmAdult: true }),
    });
    const shown = (await get('/api/v2/me/home', newIp(), cookie)).json();
    expect(shown.updates.map((u: { mod: { id: number } }) => u.mod.id)).toEqual([nsfw.id]);
  });

  it('PATCH /me/profile edits the profile, pins own published mods and attaches uploaded images', async () => {
    const fixture = bunHash('argon2id-ascii');
    const owner = await userWithPassword(fixture.hash);
    const other = await f.user();
    const first = await f.mod({ userId: owner.id });
    const second = await f.mod({ userId: owner.id });
    const draft = await f.mod({ userId: owner.id, status: 'pending' });
    const foreign = await f.mod({ userId: other.id });
    const imageUpload = async (userId: number, purpose: 'avatar' | 'banner', status: 'processing' | 'pending') => {
      const mediaId = randomUUID();
      const uploadId = randomUUID();
      await t.db.db.insert(media).values({
        id: mediaId,
        ownerId: userId,
        purpose,
        sourceBucket: 'private',
        sourceKey: `incoming/${userId}/${uploadId}`,
        status: 'ready',
        width: 512,
        height: 512,
        variants: [{ key: `media/${mediaId}/w256.webp`, w: 256, format: 'webp', bytes: 1000 }],
      });
      await t.db.db.insert(upload).values({
        id: uploadId,
        userId,
        purpose,
        bucket: 'private',
        key: `incoming/${userId}/${uploadId}`,
        filename: `${purpose}.png`,
        contentType: 'image/png',
        declaredBytes: 1000,
        maxBytes: 5_000_000,
        status,
        resultRef: { mediaId },
        expiresAt: new Date(Date.now() + 86_400_000),
      });
      return { uploadId, mediaId };
    };
    const avatar = await imageUpload(owner.id, 'avatar', 'processing');
    const banner = await imageUpload(owner.id, 'banner', 'processing');
    const foreignAvatar = await imageUpload(other.id, 'avatar', 'processing');
    const unfinished = await imageUpload(owner.id, 'avatar', 'pending');

    const cookie = sessionCookieOf(await login(owner.email, fixture.password));
    const patch = (body: unknown) =>
      t.app.inject({
        method: 'PATCH',
        url: '/api/v2/me/profile',
        headers: headers(newIp(), cookie),
        payload: JSON.stringify(body),
      });

    clearCaches();
    const res = await patch({
      displayName: '  Axel Builder ',
      bioMd: 'Modding **SOTF** since 2023.',
      links: [{ kind: 'github', url: 'https://github.com/example', label: ' Code ' }],
      pinnedModIds: [second.id, first.id],
      avatarUploadId: avatar.uploadId,
      bannerUploadId: banner.uploadId,
      bannerSeed: 1234,
    });
    expect(res.statusCode).toBe(200);
    expect(res.headers['cache-control']).toContain('no-store');
    const profile = res.json();
    expect(profile).toMatchObject({
      id: owner.id,
      handle: owner.slug,
      displayName: 'Axel Builder',
      bioMd: 'Modding **SOTF** since 2023.',
      bannerSeed: 1234,
      links: [{ kind: 'github', url: 'https://github.com/example', label: 'Code' }],
    });
    expect(profile.bioHtml).toContain('SOTF');
    expect(profile.pinnedMods.map((m: { id: number }) => m.id)).toEqual([second.id, first.id]);
    expect(profile.avatar).not.toBeNull();
    expect(profile.banner).not.toBeNull();

    const [stored] = await t.db.db.select().from(user).where(eq(user.id, owner.id));
    expect(stored).toMatchObject({
      avatarMediaId: avatar.mediaId,
      bannerMediaId: banner.mediaId,
      pinnedModIds: [second.id, first.id],
    });
    const events = await t.db.pool.query(
      `SELECT data->'payload' AS payload FROM pgboss.job
        WHERE name = 'domain.event' AND data->>'type' = 'user.profile_updated'
          AND (data->'payload'->>'userId')::int = $1`,
      [owner.id],
    );
    expect(events.rows.map((r) => r.payload)).toEqual([{ userId: owner.id, completed: true }]);

    const invalidPins = [[foreign.id], [draft.id], [first.id, first.id]];
    for (const pinnedModIds of invalidPins) {
      const bad = await patch({ pinnedModIds });
      expect(bad.statusCode).toBe(422);
      expect(bad.json().code).toBe('VALIDATION_FAILED');
    }
    expect((await patch({ avatarUploadId: foreignAvatar.uploadId })).json().code).toBe('NOT_FOUND');
    expect((await patch({ avatarUploadId: randomUUID() })).json().code).toBe('NOT_FOUND');
    expect((await patch({ avatarUploadId: unfinished.uploadId })).json().code).toBe('VALIDATION_FAILED');
    expect((await patch({ bannerUploadId: avatar.uploadId })).json().code).toBe('VALIDATION_FAILED');
    expect((await patch({ bioMd: 'x'.repeat(501) })).statusCode).toBe(422);
    expect((await patch({ unknown: true })).statusCode).toBe(422);

    // The cached profile of the first edit is evicted: the response reflects every later change.
    const cleared = await patch({
      displayName: 'Axel',
      avatarUploadId: null,
      bannerUploadId: null,
      bioMd: '   ',
      pinnedModIds: [],
    });
    expect(cleared.statusCode).toBe(200);
    expect(cleared.json()).toMatchObject({
      displayName: 'Axel',
      avatar: null,
      banner: null,
      bioMd: null,
      bioHtml: null,
      pinnedMods: [],
    });
    const [after] = await t.db.db.select().from(user).where(eq(user.id, owner.id));
    expect(after).toMatchObject({ avatarMediaId: null, bannerMediaId: null, imageUrl: '', bioMd: null });

    expect(
      (await t.app.inject({ method: 'PATCH', url: '/api/v2/me/profile', headers: headers(newIp()), payload: '{}' }))
        .statusCode,
    ).toBe(401);
  });

  it('requires a session', async () => {
    expect((await get('/api/v2/me', newIp())).statusCode).toBe(401);
    expect((await post('/api/v2/auth/email/resend', {}, newIp())).statusCode).toBe(401);
  });
});
