/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as BasecampRouteImport } from './routes/basecamp.tsx'
import { Route as MeRouteImport } from './routes/me.tsx'
import { Route as RangerRouteImport } from './routes/ranger.tsx'
import { Route as SettingsRouteImport } from './routes/settings.tsx'
import { Route as SignalsRouteImport } from './routes/signals.tsx'
import { Route as MeKitsIndexRouteImport } from './routes/me/kits/index.tsx'
import { Route as MeKitsKitIdRouteImport } from './routes/me/kits/$kitId.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BasecampRoute = BasecampRouteImport.update({
  id: '/basecamp',
  path: '/basecamp',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const RangerRoute = RangerRouteImport.update({
  id: '/ranger',
  path: '/ranger',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const MeKitsIndexRoute = MeKitsIndexRouteImport.update({
  id: '/kits/',
  path: '/kits/',
  getParentRoute: () => MeRoute,
} as any)
const MeKitsKitIdRoute = MeKitsKitIdRouteImport.update({
  id: '/kits/$kitId',
  path: '/kits/$kitId',
  getParentRoute: () => MeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basecamp': typeof BasecampRoute
  '/me': typeof MeRouteWithChildren
  '/ranger': typeof RangerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/me/kits/$kitId': typeof MeKitsKitIdRoute
  '/me/kits/': typeof MeKitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basecamp': typeof BasecampRoute
  '/me': typeof MeRouteWithChildren
  '/ranger': typeof RangerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/me/kits/$kitId': typeof MeKitsKitIdRoute
  '/me/kits': typeof MeKitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basecamp': typeof BasecampRoute
  '/me': typeof MeRouteWithChildren
  '/ranger': typeof RangerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/me/kits/$kitId': typeof MeKitsKitIdRoute
  '/me/kits/': typeof MeKitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basecamp'
    | '/me'
    | '/ranger'
    | '/settings'
    | '/signals'
    | '/me/kits/$kitId'
    | '/me/kits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basecamp'
    | '/me'
    | '/ranger'
    | '/settings'
    | '/signals'
    | '/me/kits/$kitId'
    | '/me/kits'
  id:
    | '__root__'
    | '/'
    | '/basecamp'
    | '/me'
    | '/ranger'
    | '/settings'
    | '/signals'
    | '/me/kits/$kitId'
    | '/me/kits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasecampRoute: typeof BasecampRoute
  MeRoute: typeof MeRouteWithChildren
  RangerRoute: typeof RangerRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basecamp': {
      id: '/basecamp'
      path: '/basecamp'
      fullPath: '/basecamp'
      preLoaderRoute: typeof BasecampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranger': {
      id: '/ranger'
      path: '/ranger'
      fullPath: '/ranger'
      preLoaderRoute: typeof RangerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/kits/': {
      id: '/me/kits/'
      path: '/kits'
      fullPath: '/me/kits/'
      preLoaderRoute: typeof MeKitsIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/kits/$kitId': {
      id: '/me/kits/$kitId'
      path: '/kits/$kitId'
      fullPath: '/me/kits/$kitId'
      preLoaderRoute: typeof MeKitsKitIdRouteImport
      parentRoute: typeof MeRoute
    }
  }
}

interface MeRouteChildren {
  MeKitsKitIdRoute: typeof MeKitsKitIdRoute
  MeKitsIndexRoute: typeof MeKitsIndexRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeKitsKitIdRoute: MeKitsKitIdRoute,
  MeKitsIndexRoute: MeKitsIndexRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasecampRoute: BasecampRoute,
  MeRoute: MeRouteWithChildren,
  RangerRoute: RangerRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
