/**
 * Renders the taxonomy seed (src/seed/taxonomy.ts) as the SQL of migration 0025 and its down.
 *
 * - Idempotent upserts keyed on the legacy unique slugs. Existing legacy rows (`library`, `misc`,
 *   `model-swap` in production) only receive the new v2 columns; their legacy columns (name,
 *   description, type, updatedAt) are never rewritten (PLAN §14.5). Translations already present
 *   win over the seed (`seed || existing`), so admin edits survive a re-run.
 * - The ids of the rows the seed *inserted* are recorded in "MigrationRun" (the `xmax = 0` test
 *   tells inserted from updated rows), so the down file deletes exactly those rows, and only while
 *   nothing references them.
 */
import {
  RETIRED_CATEGORY_SLUGS,
  SEED_CATEGORIES,
  SEED_LOADER_RELEASES,
  SEED_LOCALES,
  SEED_TAGS,
  type SeedCategory,
  type SeedTag,
} from './taxonomy.ts';

export const TAXONOMY_MIGRATION = '0025_seed_taxonomy';

/** Keys under which the inserted ids are recorded in "MigrationRun"."name". */
export const SEED_RUN_NAMES = {
  categories: `${TAXONOMY_MIGRATION}:categories`,
  tags: `${TAXONOMY_MIGRATION}:tags`,
  loaderReleases: `${TAXONOMY_MIGRATION}:loader-releases`,
} as const;

/** SQL string literal (standard_conforming_strings is on in every supported PostgreSQL). */
export function sqlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function sqlJson(value: unknown): string {
  return `${sqlString(JSON.stringify(value))}::jsonb`;
}

function sqlTextArray(values: readonly string[]): string {
  return values.length === 0 ? `'{}'::text[]` : `ARRAY[${values.map(sqlString).join(', ')}]::text[]`;
}

function categoryI18n(c: SeedCategory): Record<string, { name: string; description: string }> {
  return Object.fromEntries(SEED_LOCALES.map((lc) => [lc, c.i18n[lc]]));
}

function tagI18n(t: SeedTag): Record<string, { name: string }> {
  return Object.fromEntries(SEED_LOCALES.map((lc) => [lc, { name: t.names[lc] }]));
}

/** Records the ids inserted by an upsert CTE named `upserted`. */
function recordInserted(runName: string): string {
  return [
    `INSERT INTO "MigrationRun" ("name", "finishedAt", "rowsAffected", "notes")`,
    `SELECT ${sqlString(runName)}, now(), count(*),`,
    `  jsonb_build_object('insertedIds', coalesce(jsonb_agg("id" ORDER BY "id") FILTER (WHERE "inserted"), '[]'::jsonb))`,
    'FROM upserted;',
  ].join('\n');
}

export function renderTaxonomyUp(): string {
  const categoryValues = SEED_CATEGORIES.map((c) =>
    [
      '  (',
      [
        sqlString(c.legacyName),
        sqlString(c.slug),
        sqlString(c.i18n.en.description),
        `'Mod'`,
        sqlString(c.icon),
        String(c.sortOrder),
        sqlJson(categoryI18n(c)),
        sqlTextArray(c.legacySlugs),
      ].join(', '),
      ')',
    ].join(''),
  ).join(',\n');

  const tagValues = SEED_TAGS.map((t) =>
    [
      '  (',
      [
        sqlString(t.names.en),
        sqlString(t.slug),
        sqlString(t.description),
        sqlString(t.group),
        sqlJson(tagI18n(t)),
        'true',
        String(t.sortOrder),
      ].join(', '),
      ')',
    ].join(''),
  ).join(',\n');

  const loaderValues = SEED_LOADER_RELEASES.map(
    (r) => `  (${sqlString(r.name)}, ${sqlString(r.version)}, DATE ${sqlString(r.releasedAt)}, ${sqlString(r.url)})`,
  ).join(',\n');

  return `-- Code generated by \`pnpm --filter @sotf/db gen\` (scripts/gen-seed-sql.ts) from
-- src/seed/taxonomy.ts. DO NOT EDIT. Frozen once applied in production: add a new migration.
--
-- Idempotent seed of the v2 taxonomy (PLAN T0-06): ${SEED_CATEGORIES.length} mod categories, ${SEED_TAGS.length} curated tags and
-- RedLoader ${SEED_LOADER_RELEASES.map((r) => r.version).join(', ')} (PLAN §7.10). Legacy rows keep their legacy columns; only v2 columns are
-- filled, and translations already present win.

WITH upserted AS (
  INSERT INTO "Category" ("name", "slug", "description", "type", "icon", "sortOrder", "i18n", "legacySlugs")
  VALUES
${categoryValues}
  ON CONFLICT ("slug") DO UPDATE SET
    "icon" = coalesce("Category"."icon", EXCLUDED."icon"),
    "sortOrder" = CASE WHEN "Category"."sortOrder" = 0 THEN EXCLUDED."sortOrder" ELSE "Category"."sortOrder" END,
    "i18n" = EXCLUDED."i18n" || "Category"."i18n",
    "legacySlugs" = ARRAY(SELECT DISTINCT s FROM unnest("Category"."legacySlugs" || EXCLUDED."legacySlugs") AS s ORDER BY s)
  RETURNING "id", (xmax = 0) AS "inserted"
)
${recordInserted(SEED_RUN_NAMES.categories)}

-- Superseded legacy categories stay (their mods keep a valid "categoryId") but leave the v2
-- taxonomy; they resolve to the category that lists their slug in "legacySlugs".
UPDATE "Category" AS c
SET "retiredAt" = now() AT TIME ZONE 'UTC'
WHERE c."slug" IN (${RETIRED_CATEGORY_SLUGS.map(sqlString).join(', ')})
  AND c."retiredAt" IS NULL
  AND EXISTS (SELECT 1 FROM "Category" AS r WHERE c."slug" = ANY (r."legacySlugs"));

WITH upserted AS (
  INSERT INTO "Tag" ("name", "slug", "description", "group", "i18n", "isCurated", "sortOrder")
  VALUES
${tagValues}
  ON CONFLICT ("slug") DO UPDATE SET
    "group" = coalesce("Tag"."group", EXCLUDED."group"),
    "i18n" = EXCLUDED."i18n" || "Tag"."i18n",
    "isCurated" = true,
    "sortOrder" = CASE WHEN "Tag"."sortOrder" = 0 THEN EXCLUDED."sortOrder" ELSE "Tag"."sortOrder" END
  RETURNING "id", (xmax = 0) AS "inserted"
)
${recordInserted(SEED_RUN_NAMES.tags)}

WITH upserted AS (
  INSERT INTO "LoaderRelease" ("name", "version", "releasedAt", "url")
  VALUES
${loaderValues}
  ON CONFLICT ("name", "version") DO UPDATE SET
    "releasedAt" = coalesce("LoaderRelease"."releasedAt", EXCLUDED."releasedAt"),
    "url" = coalesce("LoaderRelease"."url", EXCLUDED."url")
  RETURNING "id", (xmax = 0) AS "inserted"
)
${recordInserted(SEED_RUN_NAMES.loaderReleases)}
`;
}

function insertedIds(runName: string): string {
  return `SELECT (jsonb_array_elements_text(r."notes" -> 'insertedIds'))::integer FROM "MigrationRun" AS r WHERE r."name" = ${sqlString(runName)}`;
}

export function renderTaxonomyDown(): string {
  return `-- Code generated by \`pnpm --filter @sotf/db gen\` (scripts/gen-seed-sql.ts). DO NOT EDIT.
-- sotf:allow-legacy-delete: removes only the "Category"/"Tag" rows that 0025 inserted (ids recorded in "MigrationRun") and that nothing references.
--
-- Rows that existed before the seed are left untouched (their v2 columns are dropped by the down
-- files of 0009). "retiredAt" disappears with its column.

DELETE FROM "LoaderRelease" AS l
WHERE l."id" IN (${insertedIds(SEED_RUN_NAMES.loaderReleases)})
  AND NOT EXISTS (SELECT 1 FROM "EcosystemStatus" AS e WHERE e."loaderReleaseId" = l."id");

DELETE FROM "Tag" AS t
WHERE t."id" IN (${insertedIds(SEED_RUN_NAMES.tags)})
  AND NOT EXISTS (SELECT 1 FROM "_ModToTag" AS mt WHERE mt."B" = t."id");

DELETE FROM "Category" AS c
WHERE c."id" IN (${insertedIds(SEED_RUN_NAMES.categories)})
  AND NOT EXISTS (SELECT 1 FROM "Mod" AS m WHERE m."categoryId" = c."id");

DELETE FROM "MigrationRun"
WHERE "name" IN (${Object.values(SEED_RUN_NAMES).map(sqlString).join(', ')});
`;
}
