/**
 * `GET /llms-full.txt` (PLAN §8.7): every published mod, library and build in compact Markdown.
 * Regenerated by tag (`sitemap`, `list:*`: purged whenever content is published or edited).
 */
import type { APIRoute } from 'astro';
import { loadEnv } from '../lib/env.ts';
import { allCards } from '../lib/seo/data.ts';
import { llmsFullTxt } from '../lib/seo/llms.ts';
import { CONTENT_TYPES, machineResponse, machineUnavailable } from '../lib/seo/respond.ts';

export const prerender = false;

export const GET: APIRoute = async (context) => {
  try {
    const cards = await allCards();
    const body = llmsFullTxt({ siteUrl: loadEnv().siteUrl, cards, now: new Date() });
    return machineResponse(context, body, {
      contentType: CONTENT_TYPES.text,
      tags: ['sitemap', 'list:mods', 'list:builds'],
    });
  } catch (error) {
    console.error('[web] llms-full.txt failed', error);
    return machineUnavailable();
  }
};
