/**
 * Site-wide constants shared by the layout, SEO helpers and scripts (PLAN §3.1, §4.4, §4.5).
 * No environment access here: origins that change per environment come from `env.ts`.
 */

/** Production origin; the canonical host of every indexable URL. */
export const PRODUCTION_ORIGIN = 'https://sotf-mods.com';

/** Entity identity used by JSON-LD (`Organization.sameAs`) and the footer. */
export const SOCIAL_LINKS = {
  discord: 'https://discord.gg/sotf',
  github: 'https://github.com/ChoqueCastroLD/sotf-mods-api',
} as const;

/** Steam app of Sons of the Forest (JSON-LD `about: VideoGame`). */
export const STEAM_APP_URL = 'https://store.steampowered.com/app/1326470/Sons_Of_The_Forest/';

/** Default Open Graph image (PLAN §2.8 point 3, generated by WP-01). */
export const OG_DEFAULT_PATH = '/brand/og-default.png';
export const OG_DEFAULT_SIZE = { width: 1200, height: 630 } as const;

/** Logo used by `Organization.logo`. */
export const LOGO_PATH = '/brand/logo-mark.png';

/**
 * `/ads.txt` (PLAN §4.4): byte-for-byte what the legacy site serves (58 bytes, no trailing
 * newline). Changing it breaks the AdSense seller verification.
 */
export const ADS_TXT = 'google.com, pub-2799839819522052, DIRECT, f08c47fec0942fa0';

/** Guest-hint cookie set by the API at sign-in (PLAN §5.1): readable by JS, not sensitive. */
export const SIGNED_IN_HINT_COOKIE = 'sotf_li';
